(in-package :wordle-solve)

;;;
;;; This tree was computed using the #'GREEDY-GUESS guesser
;;; and the published list of possible wordle answers.
;;;
(defvar *precomputed-tree*
  '("raise" ("yygbg" "afire") ("yyyby" "aider") ("byyyg" "aisle")
    ("bygby" "alien") ("byggb" "amiss")
    ("bygbg" "alike" ("gygbg" "agile") ("gggbg" "alive")
     ("gbgbg" "abide" ("gbgbg" "anime")))
    ("yyggg" "arise") ("bygyg" "aside") ("bgbyy" "easel")
    ("yybgg" "arose" ("ygbgg" "erase"))
    ("ybybg" "dirge" ("bygbg" "eerie") ("bgybg" "fibre")) ("ybygb" "first")
    ("yggbb" "dairy" ("bgggb" "cairn") ("bgggg" "fairy" ("bgggg" "hairy")))
    ("bbggy" "exist" ("ybggg" "heist")) ("byybg" "image" ("gbgbg" "inane"))
    ("yyybg" "irate")
    ("ygbbg" "barge" ("bggbg" "carve" ("yggbg" "farce")) ("bgggg" "large"))
    ("ygbgb" "harsh" ("bgggg" "marsh"))
    ("byyby" "email" ("ybyyg" "ideal") ("yyygb" "media")) ("ygbgg" "parse")
    ("bgbgg" "lapse" ("ygbgg" "false") ("bgbgg" "cause" ("bgbgg" "masse"))
     ("bgygg" "pause"))
    ("bbggg" "noise" ("bbggg" "guise") ("bgggg" "poise")) ("byygb" "quasi")
    ("gggbb" "rainy") ("ggbbg" "range") ("ggbyb" "raspy")
    ("ggybb" "rabid" ("gggyb" "rabbi") ("ggbgy" "radii" ("ggggb" "radio"))
     ("ggbgg" "rapid") ("ggbgb" "ratio"))
    ("ggbby" "racer" ("ggbgg" "rarer") ("ggbgb" "ramen" ("ggbgg" "raven")))
    ("ggbbb" "randy" ("ggbyb" "radar") ("gggbb" "ranch")
     ("ggbbg" "rally" ("ggbbg" "ratty")) ("ggyby" "rayon")
     ("ggbbb" "rajah" ("ggbbg" "ralph") ("ggbbb" "razor")))
    ("gbgby" "reign")
    ("gybby" "relay" ("ggbyg" "ready") ("ggyyb" "realm")
     ("ggbyb" "reach" ("ggggb" "react") ("gggbb" "rearm"))
     ("ggbgb" "rebar" ("ggbgb" "recap") ("ggygb" "rehab")) ("ggggb" "relax")
     ("ggygb" "regal" ("ggbgg" "renal")) ("ggbgg" "repay"))
    ("gbbyy" "rebus" ("ggbby" "reset")) ("gbgbb" "rhino")
    ("gbybg" "ridge" ("ggbbg" "rifle")) ("gbygg" "rinse")
    ("gbyyy" "resin" ("gygyg" "risen") ("gygyb" "riser")) ("gbyyb" "risky")
    ("gyybb" "rival")
    ("gbyby" "riper" ("gybyb" "refit" ("ggbgb" "relic") ("ggbgg" "remit"))
     ("ggggb" "ripen") ("ggbgg" "rider" ("ggbgg" "river")) ("ggbgb" "rivet"))
    ("gybgb" "roast")
    ("gbybb" "robin" ("gbbyb" "right") ("gbbgb" "rigid") ("gybyb" "rigor"))
    ("gbbgb" "roost") ("gbbgg" "reuse" ("gbggg" "rouse"))
    ("gbbby" "ruler" ("gybyg" "recur") ("gybyb" "rebut" ("ggbgg" "recut"))
     ("gbyyb" "reply") ("gybyy" "rerun") ("gbbyb" "reedy" ("ggbbb" "retch"))
     ("gbbyy" "retro" ("ggggb" "retry"))
     ("gbygb" "rebel" ("ggbgg" "repel" ("ggbgg" "revel")))
     ("gbbgb" "renew" ("gbbgb" "rodeo"))
     ("gbbgg" "roger" ("gbbgg" "refer") ("ggbgg" "rover" ("ggbgg" "rower")))
     ("ggbgg" "ruder"))
    ("gbbbb" "ruddy" ("gbbbg" "rocky" ("ggbbg" "roomy"))
     ("gbbbb" "robot" ("ggbgy" "rotor")) ("gybbb" "rough") ("gyybb" "round")
     ("gbbgg" "rowdy") ("ggbbg" "rugby") ("ggbbb" "rumor"))
    ("gbbbg" "rogue" ("gbbgg" "revue") ("gbbbg" "rhyme") ("ggyyg" "rouge")
     ("ggbyg" "route") ("gbbyg" "rupee"))
    ("gybbb" "royal" ("ggbyb" "roach") ("gbbyb" "rumba") ("gbbgg" "rural"))
    ("gbbyb" "rusty") ("bggyb" "saint") ("ygbyy" "safer" ("ggbgg" "saner"))
    ("bgbgb" "salsa" ("ygbgb" "gassy") ("ygygb" "lasso") ("bgggb" "palsy")
     ("bgbgb" "pansy" ("ggbgg" "patsy")) ("ggbgb" "sassy"))
    ("bgyyb" "basic" ("ggggb" "basil" ("ggggb" "basin" ("ggggb" "basis")))
     ("bgygb" "satin"))
    ("ygbyb" "satyr" ("ggbbg" "savor")) ("byyyy" "sepia")
    ("bbyyg" "siege" ("yybbg" "issue") ("gggbg" "sieve") ("ggbbg" "since")
     ("ggbgg" "singe"))
    ("ybgyy" "skier")
    ("bbbgb" "floss" ("ggbgb" "flush") ("gbbgy" "fussy")
     ("bbggb" "boost" ("bbggg" "ghost")) ("bgggg" "gloss") ("bbbgb" "gypsy")
     ("bbygb" "joust") ("byygb" "lousy") ("bbygy" "bossy" ("bgggg" "mossy"))
     ("bgbgb" "blush" ("bgggg" "plush")) ("bbbgy" "hussy" ("yyygb" "shush"))
     ("bgggy" "slosh") ("bgbgy" "slush"))
    ("bbgyy" "shied" ("gbggg" "spied") ("gbggb" "spiel"))
    ("ybgyg" "shire" ("gbggg" "spire")) ("yyyyb" "stair")
    ("yybyg" "scare"
     ("gbggg" "share" ("gbggg" "snare" ("gbggg" "spare" ("gbggg" "stare")))))
    ("bbyyy" "islet" ("yybyb" "sheik") ("yybgb" "sinew") ("yybyy" "stein"))
    ("bbbyg" "stone" ("ybbyg" "ensue") ("gbbgg" "scene") ("gbbbg" "segue")
     ("gbggg" "scone" ("gbggg" "shone")) ("gygbg" "smote") ("gbybg" "solve")
     ("gbgbg" "scope" ("gbggg" "slope") ("gbgbg" "shove" ("gbgbg" "smoke"))
      ("gbgyg" "spoke"))
     ("gggbg" "stoke" ("gggbg" "stole" ("gggbg" "stove"))) ("ggbbg" "style"))
    ("yybyb" "strap" ("ybyyb" "arson") ("gbggb" "scram") ("gbggg" "scrap")
     ("gbyyg" "sharp") ("gyyyb" "smart") ("gbyyy" "spark") ("gbggy" "spray")
     ("ggyyb" "stark" ("ggggb" "start")) ("ggggb" "straw" ("ggggb" "stray"))
     ("gbygb" "solar" ("ggbgg" "sonar") ("gbbgg" "sugar"))
     ("gbyyb" "scarf" ("ggggb" "scary")
      ("gbggb" "shard" ("ggggb" "shark") ("gbggb" "snarl" ("gbggb" "swarm")))))
    ("yybyy" "shear" ("gbggg" "smear" ("gbggg" "spear" ("gbggg" "swear"))))
    ("bybyy" "steak" ("ybyyb" "ashen") ("ybyyy" "askew") ("yyyyb" "asset")
     ("ybygb" "essay") ("gbygb" "sedan") ("gbggg" "sneak" ("gbggg" "speak"))
     ("ggggb" "stead" ("ggggb" "steal" ("ggggb" "steam"))) ("gyggb" "sweat"))
    ("bbgyg" "snipe" ("gggbg" "snide") ("gygyg" "spine")
     ("gbgyg" "spice" ("gggbg" "spike" ("gggbg" "spite")))
     ("gbgbg" "slime" ("gggbg" "slice" ("gggbg" "slide")) ("gygyg" "smile")
      ("gbgyg" "smite") ("gbgbg" "seize" ("gbgbg" "suite")))
     ("gygbg" "shine" ("gbggg" "swine")))
    ("ybgyb" "shirk" ("ggggb" "shirt") ("gbggy" "skirt") ("gbggg" "smirk")
     ("gbggb" "swirl"))
    ("ybbyg" "scree" ("ggybg" "score") ("gbgyg" "serve") ("gbggg" "spree")
     ("gbgbg" "surge")
     ("gbybg" "shore"
      ("gbggg" "snore" ("gbggg" "spore" ("gbggg" "store" ("gbggg" "swore"))))))
    ("bbbyb" "stunk" ("ybyyb" "bonus") ("ybbbb" "bosom")
     ("ybyby" "dusky" ("bgggg" "husky" ("bgggg" "musky")))
     ("yyybb" "dusty" ("bgggb" "gusto")
      ("bgggg" "gusty" ("bgggg" "lusty" ("bgggg" "musty"))))
     ("ybybb" "humus" ("bbbgg" "focus" ("bgggg" "locus")) ("bgbgg" "lupus")
      ("bgygg" "mucus") ("ygyby" "mushy") ("ygbby" "bushy" ("bgggg" "pushy")))
     ("gyggb" "shunt") ("gbgbg" "shuck" ("gbgbg" "skulk")) ("gbgby" "skull")
     ("gbgbb" "slump") ("gbbby" "smoky") ("gyyyb" "snout") ("gbgyg" "snuck")
     ("gbgyb" "snuff")
     ("gybbb" "shoot" ("gygby" "sloth") ("gygyy" "sooth") ("gbgyy" "sooty"))
     ("gygbb" "south")
     ("gbbbg" "shock" ("gggbg" "shook") ("gbggg" "smock") ("gbgbg" "spook"))
     ("gyybb" "scout" ("gbggg" "shout" ("gbggg" "spout")))
     ("gbggg" "skunk" ("gbggg" "slunk" ("gbggg" "spunk"))) ("ggbbg" "stock")
     ("ggbgb" "stony")
     ("ggbbb" "stomp" ("gggbb" "stood" ("ggggb" "stool")) ("gggbg" "stoop"))
     ("ggybb" "stout") ("gggbg" "stuck")
     ("gggbb" "study" ("gggbb" "stuff" ("gggbb" "stump")))
     ("ggggb" "stung" ("ggggb" "stunt")) ("gbyby" "sulky") ("gbybb" "sully")
     ("gbygb" "sunny")
     ("gbbbb" "scowl" ("gggby" "scold") ("gggbb" "scoff" ("gggbb" "scoop"))
      ("gbggb" "showy") ("gbgby" "sloop") ("gbbby" "shyly" ("gbggg" "slyly"))
      ("gbybb" "soggy") ("gbgbb" "spoof") ("gbgbg" "spool") ("gbgyb" "swoop"))
     ("gbggb" "slung" ("gbggb" "sound") ("gbggg" "swung"))
     ("gbbyb" "shown" ("gbgby" "snoop") ("gbggy" "snowy") ("gbgbg" "spoon")
      ("gbgyg" "swoon") ("gbyby" "synod")))
    ("bggbb" "faint" ("gggby" "faith") ("bggbb" "daily" ("bgggg" "gaily"))
     ("bgggg" "paint" ("bgggg" "taint")))
    ("ygybb" "nadir" ("bgbgg" "tapir"))
    ("bgbyb" "salon" ("ygybb" "basal") ("ygbgg" "mason") ("ygyby" "nasal")
     ("ygbby" "nasty") ("ggybb" "sadly")
     ("gggbb" "sally" ("gggbb" "salad") ("gggbg" "salty")) ("gggyb" "salvo")
     ("ggbby" "sandy" ("ggybb" "sauna")) ("ggbgb" "savoy")
     ("ggbbb" "sappy" ("ggbbg" "saucy" ("ggbbg" "savvy")))
     ("ygbbb" "hasty" ("bgggb" "pasta") ("bgggg" "pasty" ("bgggg" "tasty"))))
    ("bybgg" "cease" ("bbygg" "abuse" ("gbggg" "amuse")) ("gbggg" "chase")
     ("bbggg" "abase" ("bbggg" "phase")) ("bgggg" "lease" ("bgggg" "tease")))
    ("bbygb" "missy" ("bgbgb" "kiosk") ("ggbgb" "midst") ("bgggg" "sissy")
     ("bgbgg" "gipsy" ("bgggg" "tipsy")))
    ("bybgb" "slash" ("ybygb" "abyss") ("ybggb" "amass") ("bbygb" "angst")
     ("bbggy" "chasm") ("bgggg" "clash" ("bgggg" "flash"))
     ("bgggb" "blast" ("bgggb" "clasp" ("bgggb" "flask")))
     ("ygggb" "class" ("bgggg" "glass"))
     ("bbggg" "awash" ("bbggg" "gnash" ("bbggg" "quash"))) ("gbggb" "spasm")
     ("gbggg" "smash" ("gbggg" "stash" ("gbggg" "swash")))
     ("bbggb" "boast" ("bgggg" "coast" ("bgggg" "toast"))))
    ("yybbg" "grace" ("yyybg" "agree") ("ygybg" "argue")
     ("byybg" "adore" ("gbbgg" "azure"))
     ("bggyg" "crane" ("gggbg" "crate" ("gggbg" "crave" ("gggbg" "craze"))))
     ("bygbg" "blare" ("bbggg" "aware") ("bgggg" "flare")) ("gygbg" "glare")
     ("gggbg" "grade"
      ("gggbg" "grape" ("gggbg" "grate" ("gggbg" "grave" ("gggbg" "graze")))))
     ("bgggg" "brace" ("bgggg" "trace"))
     ("bggbg" "drake" ("bgggg" "brake") ("gggbg" "drape")
      ("bggbg" "brave" ("bggbg" "frame")) ("yggbg" "trade")))
    ("yybgb" "brash" ("bgygb" "artsy") ("ggggb" "brass")
     ("bgggb" "crass" ("bgggb" "grasp") ("bgggg" "grass"))
     ("bgggg" "crash" ("bgggg" "trash")))
    ("yygbb" "briar" ("bgggg" "friar") ("bgggb" "triad" ("ggggb" "trial")))
    ("bybyg" "slate" ("gygbg" "scale" ("gbggg" "shale")) ("gggbg" "slave")
     ("gygyg" "stale") ("gbggg" "skate" ("gbggg" "state"))
     ("gbgyg" "stage" ("gggbg" "stake" ("gggbg" "stave")))
     ("gbgbg" "shape"
      ("gggbg" "shade" ("gggbg" "shake" ("gggbg" "shame" ("gggbg" "shave"))))
      ("gbgyg" "space" ("gggbg" "spade")) ("gbgbg" "snake" ("gbgbg" "suave")))
     ("ybgbg" "usage"))
    ("ybbyy" "sheer" ("ybygg" "ester") ("ybbgg" "loser" ("bgggg" "poser"))
     ("gbbgy" "screw") ("gbyby" "serum") ("gbygg" "sever" ("ggbgg" "sewer"))
     ("ggbgy" "shrew") ("gbggg" "sneer" ("gbggg" "steer"))
     ("gbgby" "sperm" ("gbggb" "stern"))
     ("gbbgg" "sober" ("ggbgg" "sower") ("gbbgg" "super" ("ggbgg" "surer")))
     ("yybgg" "usher"))
    ("bbgyb" "stink" ("gbgbg" "slick") ("gbggg" "slink")
     ("gbgyb" "scion" ("gbgby" "sniff"))
     ("gbgby" "skiff" ("gggbb" "skill" ("gggbb" "skimp")) ("gygbb" "spiky"))
     ("gggbg" "stick") ("gggbb" "still" ("gggbb" "stiff") ("ggggb" "stilt"))
     ("ggggb" "sting" ("ggggb" "stint"))
     ("gygbb" "shift" ("gygby" "smith") ("gbgbg" "spilt") ("gbggg" "swift"))
     ("gbgbb" "spicy" ("gbgbg" "slimy") ("gggbb" "spill") ("gbgbb" "swill"))
     ("gbggb" "sling" ("gbggb" "shiny" ("gbggg" "spiny"))
      ("gbggg" "suing" ("gbggg" "swing")))
     ("ybggb" "using"))
    ("bybyb" "stalk" ("yyybb" "ascot") ("ybybb" "assay") ("ybgbb" "chaos")
     ("ybggb" "psalm") ("gyggb" "shalt") ("gbyyb" "shoal") ("gbgyg" "slack")
     ("gbgyb" "shawl" ("gbgby" "slang")) ("gygyb" "slant")
     ("gbggb" "scald" ("ggggb" "scalp" ("ggggb" "scaly"))
      ("gbggb" "shall" ("gbggg" "small")))
     ("gbgby" "shaky" ("gbggg" "snaky"))
     ("gbgbg" "shank" ("gggbg" "shack") ("gbgbg" "smack") ("gbgyg" "snack")
      ("gbggg" "spank"))
     ("gyyyb" "splat") ("gyybb" "squat") ("ggggb" "stall")
     ("gggbb" "staff" ("gggbb" "stamp" ("gggbb" "stand")))
     ("gggbg" "stack" ("gggbg" "stank"))
     ("gbybb" "scuba" ("gbgby" "squad") ("gyyby" "sumac"))
     ("gbgbb" "swamp" ("gbggg" "scamp") ("gbgbb" "shady") ("gbgby" "soapy")
      ("gygby" "spawn"))
     ("gygbb" "scant" ("gbgbg" "shaft") ("gbgby" "swath")) ("ybyyb" "usual"))
    ("ybbyb" "short" ("gbgyb" "scour") ("ggggb" "shorn")
     ("ggbyb" "shrub" ("ggggb" "shrug")) ("gbygb" "sorry")
     ("gbggg" "snort" ("gbggg" "sport")) ("gbbgb" "slurp" ("gbggy" "spurn"))
     ("gbbgg" "spurt") ("gbggy" "stork" ("ggggb" "storm" ("ggggb" "story")))
     ("gbbyg" "strut") ("gbggb" "scorn" ("gbggb" "sword") ("gbggg" "sworn"))
     ("gbbyb" "scrub" ("ggggb" "scrum") ("gbgyb" "surly") ("gbggb" "syrup"))
     ("ybyyy" "torus") ("ybbgb" "usurp"))
    ("bgbbg" "cable" ("ggbbg" "cache" ("ggbbg" "canoe")) ("ygbbg" "dance")
     ("ygbyg" "lance") ("bgbgg" "eagle" ("bgbgg" "ladle" ("bgbgg" "maple")))
     ("bgybg" "badge" ("ggbbg" "bathe") ("ygbbg" "maybe"))
     ("bgggg" "fable" ("bgggg" "table"))
     ("bgbbg" "gauge" ("ggbbg" "gaffe") ("gggbg" "gauze") ("bgbgg" "mange")
      ("bggbg" "haute" ("bggbg" "mauve")) ("bgbbg" "payee") ("ygybg" "vague"))
     ("bgbyg" "halve" ("ygybg" "lathe") ("bgybg" "latte") ("bggyg" "value")
      ("bgggg" "valve")))
    ("bgybb" "panic" ("bgygy" "cabin") ("bgbyy" "cacti") ("bgbgg" "magic")
     ("bgggb" "mania") ("bgggg" "manic") ("ggbgb" "patio")
     ("bgbgy" "cavil" ("ygbgb" "tacit"))
     ("bgbgb" "mafia" ("ggbgb" "maxim") ("bgbgb" "habit" ("bgbgb" "valid")))
     ("ygbgb" "vapid"))
    ("ybybb" "droit" ("byggb" "choir") ("byygb" "curio") ("gybyy" "dirty")
     ("ggbgb" "druid") ("bgbgg" "fruit") ("bgggb" "broil" ("bgggb" "groin"))
     ("bybyb" "birch" ("bggbb" "girly") ("byyyb" "incur")) ("byyyy" "intro")
     ("bggyb" "irony") ("bygyb" "ivory") ("yybgb" "lurid") ("bybgb" "lyric")
     ("bybyy" "birth" ("bgggg" "girth" ("bgggg" "mirth"))) ("bgygg" "orbit")
     ("byyyb" "micro" ("ggbyy" "minor") ("bgbyy" "vigor")))
    ("yyybb" "trail" ("byygb" "acrid") ("byggb" "chair") ("bygyb" "diary")
     ("byggy" "flair") ("bgggg" "frail" ("bgggg" "grail"))
     ("bgggb" "braid" ("ggggb" "brain") ("bgggy" "drain") ("bgggb" "grain"))
     ("gygyb" "tiara") ("ggggb" "train" ("ggggb" "trait"))
     ("byyyb" "cigar" ("ggbyy" "circa") ("ygbgg" "vicar")) ("byyyg" "viral"))
    ("ybyyb" "sprig" ("gyggb" "strip") ("ybgyb" "virus") ("ybyyb" "visor"))
    ("byyyb" "slain" ("gbyyb" "sigma") ("gyggy" "snail") ("gbggb" "staid")
     ("gbggg" "stain") ("gbgyb" "swami") ("ybyyb" "vista"))
    ("byybb" "tidal" ("yyyyb" "admit") ("bygyb" "audio") ("yygyb" "audit")
     ("byyyb" "aphid" ("gbbgy" "admin") ("gbbgg" "avoid"))
     ("yybyb" "antic" ("gbggg" "attic") ("gbygb" "await")) ("bgbgg" "final")
     ("ygbyb" "giant") ("bybgy" "inlay")
     ("bybyb" "affix" ("gbbgb" "again") ("ybbgb" "chain") ("ybbyb" "khaki"))
     ("bgbgy" "lilac") ("bgbyb" "ninja" ("ygbby" "piano") ("bgbbg" "pizza"))
     ("byyyy" "plaid") ("bybyy" "claim" ("bgggb" "plain")) ("yybyy" "plait")
     ("bybyg" "anvil" ("gbygg" "avail") ("ybbgg" "flail" ("bbggg" "quail")))
     ("ggbyb" "tibia") ("ggbgb" "titan") ("bgbyy" "villa" ("ggbgg" "viola"))
     ("ygbgg" "vital"))
    ("bygbb" "align" ("gggbb" "alibi") ("gbgyy" "aging" ("gbggg" "aping"))
     ("gygbb" "axial") ("gbgbb" "amity" ("gygbb" "axiom"))
     ("gbgbg" "avian" ("gbgbg" "axion")) ("ybgby" "china") ("yggbb" "iliac")
     ("yygbb" "voila"))
    ("bgggb" "daisy" ("bgggb" "waist"))
    ("bggbg" "naive" ("bggbg" "maize") ("bgggg" "waive"))
    ("ygbbb" "party" ("yggbg" "harpy")
     ("bggbb" "carol" ("bgggb" "baron") ("gggyb" "cargo") ("bggbb" "karma")
      ("bggby" "larva") ("yggbb" "march"))
     ("bggbg" "carry" ("bggbg" "hardy") ("bgggg" "harry" ("bgggg" "marry")))
     ("bgyby" "mayor") ("gggbb" "parka") ("gggbg" "parry") ("bggyg" "tardy")
     ("bggyb" "carat" ("bggbg" "tarot"))
     ("bgybb" "valor" ("ygbgg" "favor") ("bgygg" "labor") ("bgbyy" "macro")
      ("bgbgg" "major" ("ggbgg" "manor")))
     ("ygybb" "vapor") ("bgggg" "warty"))
    ("bgbyg" "caste" ("bgybg" "salve") ("ygybg" "sauce") ("bgygg" "saute")
     ("bgggg" "baste"
      ("bgggg" "haste" ("bgggg" "paste" ("bgggg" "taste" ("bgggg" "waste"))))))
    ("ygbby" "taper" ("bgbyy" "early") ("ygbyy" "earth") ("bgbgy" "harem")
     ("bgggg" "caper" ("bgggg" "paper"))
     ("bgygg" "paler" ("ggbgg" "parer" ("ggbgg" "payer")))
     ("ggbgg" "taker" ("ggbgg" "tamer"))
     ("ygbgg" "cater"
      ("bgggg" "eater" ("bgggg" "hater" ("bgggg" "later" ("bgggg" "water")))))
     ("bgbgg" "lager" ("ygbgg" "baler")
      ("bgygg" "gamer" ("ggbgg" "gayer" ("ggbgg" "gazer"))) ("ggbgg" "layer")
      ("bgggg" "eager" ("bgggg" "wager"))
      ("bgbgg" "baker" ("bgggg" "maker") ("bgbgg" "wafer" ("ggbgg" "waver")))))
    ("bgbby" "navel" ("bgggg" "gavel") ("ygggb" "haven") ("ygbgy" "laden")
     ("bgbgg" "label" ("bgygg" "bagel") ("bgbgg" "camel" ("bgbgg" "hazel"))
      ("ggbgg" "lapel"))
     ("bgbgb" "cadet" ("ggbgb" "cagey" ("ggbgb" "cameo")) ("ygbgg" "facet")
      ("bgbgy" "matey"))
     ("ygbgg" "panel") ("bgygy" "valet")
     ("ygbgb" "taken" ("ygbgg" "eaten") ("bgggg" "oaken") ("bgbgg" "waxen")))
    ("bbgby" "edict" ("ybgyb" "chief") ("yygby" "deity") ("gggbb" "edify")
     ("gbggg" "evict") ("gbgbb" "eking" ("gbggg" "eying"))
     ("yygbb" "deign" ("yygbb" "plied")) ("ybgbg" "quiet") ("ybgby" "thief")
     ("ybgbb" "feign" ("bggyy" "being") ("bgggy" "neigh") ("bgggb" "weigh")))
    ("ybgby" "fried" ("bgggb" "crier") ("bgggy" "drier") ("gyggb" "flier")
     ("ygggb" "brief" ("bgggg" "grief")) ("byggb" "plier")
     ("bgggg" "cried" ("bgggg" "dried" ("bgggg" "pried" ("bgggg" "tried"))))
     ("bygyg" "weird"))
    ("bbbgy" "chess" ("ggggb" "chest") ("byggb" "flesh")
     ("bbggg" "bless" ("bbggg" "guess"))
     ("bbggb" "guest" ("bbggb" "poesy") ("bgggg" "quest")) ("byygb" "welsh"))
    ("bybbg" "plate" ("bbygg" "acute") ("ybgbg" "agape")
     ("bgybg" "algae" ("ggbbg" "alone"))
     ("byybg" "angle" ("gbbgg" "amble") ("ggbgg" "ankle"))
     ("yyybg" "ample" ("gbggg" "apple")) ("bbyyg" "atone")
     ("bbybg" "abode" ("gggbg" "above") ("gygyg" "adobe") ("gbggg" "anode")
      ("gbgbg" "awoke"))
     ("bgggg" "elate")
     ("bggbg" "blade" ("gggbg" "blame" ("gggbg" "blaze")) ("bgggg" "glade")
      ("bggbg" "flake" ("gggbg" "flame") ("bggbg" "glaze")))
     ("bbggg" "abate" ("gbggg" "agate") ("bbggg" "ovate")) ("gbgbg" "peace")
     ("gggbg" "place" ("gggbg" "plane"))
     ("bbgbg" "awake" ("gbgbg" "adage" ("gbgbg" "amaze"))
      ("bbgbg" "chafe" ("bbgbg" "evade") ("bygbg" "heave")) ("bbgyg" "knave")
      ("bbggg" "quake") ("bygbg" "weave"))
     ("bygbg" "leave" ("ybgbg" "whale")))
    ("bybby" "cleat" ("bbgyg" "adept" ("gbgbg" "agent")) ("bgyyb" "alley")
     ("bbygg" "begat") ("gbggb" "cheap") ("gbggg" "cheat") ("ggggb" "clean")
     ("byyyy" "delta") ("yyygg" "eclat") ("ybyyg" "enact" ("gbggg" "exact"))
     ("yyygb" "decal" ("bgggg" "fecal"))
     ("bbyyb" "beady" ("yyybg" "abbey") ("byybb" "annex" ("gbggb" "apnea"))
      ("bgggg" "heady") ("bggbg" "heavy"))
     ("bbggb" "ahead" ("bbggg" "knead")) ("yyyyb" "leach")
     ("byyyg" "leant" ("yggbg" "dealt") ("yygbg" "exalt") ("gggbg" "leapt"))
     ("byyyb" "fella" ("bygby" "abled") ("byyby" "angel") ("ygyby" "leafy")
      ("bgyby" "leaky") ("bgbgy" "mealy"))
     ("bbyyg" "meant") ("bbyyy" "death" ("bgggg" "heath") ("bgggb" "meaty"))
     ("ybggb" "ocean")
     ("bbgyb" "amend" ("yygyb" "enema") ("ybggb" "hyena") ("yggbb" "omega"))
     ("ybyyb" "beach" ("bgygb" "mecca") ("bgggg" "peach"))
     ("ybygb" "decay" ("bgggb" "pecan"))
     ("byygb" "pedal" ("bgygy" "delay") ("bybgg" "equal") ("bgbgg" "legal")
      ("bgggg" "medal") ("ggbgg" "penal"))
     ("byygy" "fetal" ("bgggg" "metal" ("bgggg" "petal")))
     ("bgggb" "gleam" ("ggggb" "glean") ("bgggb" "bleak" ("bgggb" "plead")))
     ("bgggg" "bleat" ("bgggg" "pleat")) ("ybyyy" "teach") ("bbgyy" "theta")
     ("bbggy" "tweak") ("bbygb" "began" ("ygbgb" "kebab") ("bgggg" "vegan"))
     ("bbggg" "wheat"))
    ("bbgbb" "cling" ("bggbb" "blimp" ("gggbb" "blitz")) ("gbgbb" "chick")
     ("gygbb" "child" ("ggggb" "chili" ("ggggb" "chill")))
     ("gggbb" "click" ("gggbb" "cliff" ("gggbb" "climb"))) ("ggggb" "clink")
     ("yggbb" "flick") ("bgggg" "fling")
     ("bgggb" "blind" ("ggggb" "blink") ("bgggb" "flint")) ("bgggy" "glint")
     ("bygby" "guild" ("ggggb" "guilt")) ("yygbb" "icily") ("ybggg" "icing")
     ("byggg" "lying")
     ("bygbb" "built" ("ggggb" "build") ("bgggb" "quill") ("bgggg" "quilt"))
     ("bbgby" "thigh")
     ("bbgyb" "unify" ("bggbb" "onion") ("gggbb" "union") ("gggbg" "unity"))
     ("bbggg" "doing" ("gbggg" "dying") ("bgggg" "going") ("byggg" "owing")
      ("bbggg" "thing" ("gbggg" "tying") ("bbggg" "vying")))
     ("ybgbb" "quick" ("bgggb" "juicy") ("bbggg" "thick") ("bbggb" "which"))
     ("bbgbb" "idiot" ("ggggb" "idiom") ("bbgyb" "opium") ("bbgbg" "twixt")
      ("bbgbb" "whiff"))
     ("bbggb" "joint" ("bgggg" "point") ("bbggy" "think") ("bbggb" "whiny")))
    ("bbggb" "hoist" ("bbggb" "bliss")
     ("bgggg" "foist" ("bgggg" "joist" ("bgggg" "moist"))) ("bgggb" "noisy")
     ("bbggg" "twist") ("ybggb" "swish" ("byggy" "whisk")))
    ("bbgbg" "utile" ("bygyg" "elite") ("ybggg" "guile")
     ("ybgbg" "guide" ("bggbg" "juice"))
     ("bbgyg" "elide" ("bgggg" "glide") ("bggbg" "olive")) ("yygbg" "quite")
     ("gygbg" "unite") ("bbggg" "exile" ("bbggg" "while"))
     ("bbgbg" "opine" ("bbgbg" "chide" ("gggbg" "chime")) ("bbgyg" "knife")
      ("gbggg" "ovine") ("gbgbg" "oxide") ("ybgbg" "voice") ("bbggg" "whine"))
     ("bygbg" "twice" ("gggbg" "twine") ("yygbg" "white")))
    ("bbbbg" "lunge" ("ygbyg" "bugle") ("ygbgg" "bulge")
     ("bybbg" "chute" ("gbgbg" "coupe") ("ybgbg" "deuce") ("bbgyg" "etude"))
     ("bgbyg" "fugue") ("ybbyg" "globe" ("gggbg" "glove")) ("bbyyg" "gnome")
     ("bybgg" "gouge") ("bgbgg" "budge" ("bgggg" "fudge" ("bgggg" "judge")))
     ("gbbgg" "ledge" ("gbggg" "lodge")) ("ybybg" "clone" ("byyyg" "noble"))
     ("bgygg" "nudge") ("bggbg" "dunce" ("bgggg" "ounce"))
     ("bbgbg" "fence" ("bgggg" "hence" ("bgggg" "pence")) ("bggbg" "penne"))
     ("bbybg" "ozone" ("bbggg" "phone"))
     ("yybbg" "flume" ("bygbg" "boule") ("bggbg" "elude")
      ("gggbg" "fluke" ("gggbg" "flute")) ("bgggg" "plume"))
     ("bgbbg" "butte" ("bgbbg" "queue") ("bgbgg" "quote"))
     ("bbbbg" "theme" ("bbbbg" "booze") ("bgbbg" "choke") ("bbyyg" "emcee")
      ("bbybg" "evoke") ("bbygg" "femme") ("gbybg" "tepee") ("ggbgg" "thyme"))
     ("ygbbg" "tulle") ("yyybg" "uncle") ("byybg" "undue") ("bygbg" "venue")
     ("bybyg" "vogue") ("bbbgg" "hedge" ("bbggg" "dodge") ("bgggg" "wedge"))
     ("ybbbg" "belle" ("gbybg" "bloke") ("bbybg" "clove") ("byybg" "elope")
      ("bggbg" "delve" ("bggbg" "melee")) ("bbbgg" "cycle" ("bbbgg" "whole"))))
    ("bbbgg" "loose" ("ybggg" "close") ("ggbgg" "louse")
     ("bgggg" "goose" ("bgggg" "moose" ("bgggg" "noose"))) ("bybgg" "obese")
     ("bgbgg" "copse" ("bgbgg" "house" ("bgggg" "mouse")) ("bgygg" "posse"))
     ("ybbgg" "pulse")
     ("bbbgg" "dense" ("bgbgg" "geese") ("bgggg" "sense" ("bgggg" "tense"))
      ("bybgg" "these"))
     ("bbggg" "chose" ("bgggg" "those" ("bgggg" "whose"))))
    ("ybyby" "diner" ("ggbgg" "diver") ("bgbyy" "fiery") ("yybgg" "idler")
     ("byyyy" "inert") ("byggg" "inner") ("byygg" "infer" ("ggbgg" "inter"))
     ("bgggg" "finer" ("bgggg" "liner" ("bgggg" "miner"))) ("bgygg" "nicer")
     ("bybyy" "merit" ("bgggb" "peril")) ("bybyg" "their")
     ("bgbgg" "giver" ("bgggg" "liver") ("ygbgg" "tiger")
      ("bgbgg" "fiber" ("ggbgg" "filer" ("ggbgg" "fixer"))
               ("bgbgg" "piper" ("bgbgg" "timer")))
      ("bgygg" "viper"))
     ("ygbgg" "cider" ("bgggg" "wider")))
    ("bbybg" "binge" ("gybbg" "belie") ("ggbgg" "bilge")
     ("ggbbg" "bible" ("ggbbg" "biome")) ("bygyg" "genie") ("bgggg" "hinge")
     ("yybbg" "imbue") ("bgbgg" "liege" ("bgbgg" "midge"))
     ("bybbg" "cutie" ("bbbgg" "movie")) ("bgybg" "niche" ("ggybg" "niece"))
     ("bgbbg" "tilde" ("bgbgg" "diode") ("ygybg" "lithe")
      ("bgbbg" "piece" ("ggbbg" "pique" ("ggbbg" "pixie"))) ("ggbbg" "tithe")
      ("ggybg" "title"))
     ("byybg" "untie") ("bggbg" "mince" ("bgggg" "wince")))
    ("ybyyy" "miser" ("byyyy" "serif") ("bgygy" "siren") ("bgggg" "wiser"))
    ("bbyyb" "stoic" ("ybyyb" "bison") ("ybyyy" "disco") ("ybbyy" "ficus")
     ("ybbgg" "music") ("yyygb" "posit")
     ("gybyb" "sight" ("ggbyy" "sixth") ("ggbby" "sixty")) ("gbygb" "solid")
     ("gbygg" "sonic") ("gybgb" "split") ("gbggb" "spoil") ("gbbgb" "squib")
     ("gbbyb" "silky" ("gggbg" "silly") ("gybbb" "sushi")) ("yybgb" "visit")
     ("ybbyb" "fishy" ("bgybb" "minus") ("bggbg" "wispy")))
    ("bbybb" "pilot" ("bgbgg" "bigot") ("bgbyb" "bingo" ("bgggg" "dingo"))
     ("bgbyy" "ditto") ("bggby" "filth") ("bygyb" "folio") ("ygbyb" "hippo")
     ("byggb" "igloo") ("yyybb" "imply") ("bybgb" "inbox") ("bybgg" "ingot")
     ("yybbg" "input") ("bgybg" "light" ("ggbbg" "limit"))
     ("bgyyb" "limbo" ("ggbbg" "lingo")) ("ygybb" "lipid")
     ("byyyb" "logic" ("ggggb" "login"))
     ("byybb" "fluid" ("bybyy" "idyll") ("byygg" "lucid"))
     ("bybyb" "comic" ("ggbgg" "conic") ("bgbgg" "ionic") ("bybgb" "ovoid"))
     ("ggbbb" "picky" ("ggbbg" "piggy") ("ggybb" "pinch") ("ggbgg" "pinky"))
     ("ggbyy" "pinto") ("ggbby" "pitch" ("gggby" "pithy")) ("ggbgg" "pivot")
     ("gybbb" "pubic") ("gyybb" "pupil") ("yybyy" "optic" ("yyygg" "topic"))
     ("bybyy" "tonic" ("ygbgb" "motif") ("ggbgg" "toxic") ("ggygb" "toxin"))
     ("yygby" "tulip") ("bybby" "itchy" ("yyybb" "tunic"))
     ("bybbb" "cubic" ("ggbgb" "cumin") ("gbbgg" "cynic") ("bgbyb" "fungi")
      ("bgbgb" "humid") ("bybgb" "undid"))
     ("bybbg" "unfit") ("bygbg" "unlit") ("byyby" "until") ("yybbb" "unzip")
     ("bgybb" "civil" ("bgbby" "dimly") ("bgggy" "livid") ("bgygg" "vigil")
      ("bgybg" "vinyl"))
     ("bybyg" "vomit") ("bgbgb" "widow")
     ("bgbbg" "fight" ("bggbg" "digit")
      ("bgggg" "might" ("bgggg" "night" ("bgggg" "tight" ("bgggg" "wight")))))
     ("bggbb" "filly" ("gggbg" "filmy") ("bggbg" "milky")
      ("bgggg" "billy" ("bgggg" "dilly" ("bgggg" "hilly" ("bgggg" "willy")))))
     ("ygbbb" "hippy" ("bgbgg" "wimpy"))
     ("bgbbb" "windy" ("bggyg" "dingy") ("bgbyg" "dizzy")
      ("bgbgg" "biddy" ("bgggg" "giddy")) ("bgbbg" "fizzy" ("ygbbg" "jiffy"))
      ("bgbbb" "civic" ("bgbgg" "mimic"))
      ("bggbb" "cinch" ("bgggg" "finch") ("bggbb" "minim"))
      ("bggbg" "kinky" ("bggbg" "ninny")) ("bgbyb" "vivid") ("gggbb" "winch"))
     ("bgbby" "ditch" ("gggbb" "ditty") ("bgybb" "fifty" ("bgbgg" "minty"))
      ("bgybg" "fifth" ("bgbgg" "ninth")) ("ygybb" "timid") ("ygybg" "width")
      ("bgggg" "hitch" ("bgggg" "witch"))
      ("bggbb" "bitty" ("bgggg" "kitty" ("bgggg" "witty")))))
    ("ybbgg" "curse" ("bbygg" "prose") ("bgggg" "nurse" ("bgggg" "purse"))
     ("bbggg" "horse" ("bbggg" "terse" ("bgggg" "verse")) ("bgggg" "worse")))
    ("ybbgb" "crust" ("bgggb" "brush") ("byygg" "burst") ("ggbgb" "cross")
     ("ggggb" "crush") ("bgbgb" "dross" ("bgggg" "gross")) ("bybgy" "torso")
     ("bgggy" "truss") ("bgggg" "trust") ("bgbgg" "frost" ("bgbgg" "tryst"))
     ("bybgg" "worst"))
    ("bbbby" "betel" ("ggbyb" "beech" ("gggbb" "beefy")) ("ggygb" "beget")
     ("ggbby" "belch" ("gggbb" "belly" ("gggbb" "below")))
     ("ggbbb" "begun" ("ggbby" "bench")) ("ggbgg" "bevel" ("ggbgg" "bezel"))
     ("gybgy" "bleed" ("ggggb" "bleep")) ("gybby" "blend") ("gbbgb" "boney")
     ("gbbgg" "bowel") ("ygbbb" "debug") ("ygybb" "debut") ("yybbb" "ebony")
     ("yybby" "elbow") ("byyyy" "elect") ("bybyy" "elegy") ("yybgb" "embed")
     ("bybyb" "enemy")
     ("bybbb" "enjoy" ("ybbbb" "check") ("ggbgb" "endow") ("ggbbg" "enemy")
      ("ggbgg" "envoy") ("gbbyb" "epoch") ("gbbyg" "epoxy"))
     ("byyyb" "eject" ("gbgbg" "event")) ("bygbg" "extol") ("byygy" "fleet")
     ("byyby" "cleft" ("yggbg" "elect") ("byybg" "exult")
      ("bygbg" "dwelt" ("bbggg" "knelt")))
     ("bgbyy" "leech") ("bgyby" "lefty") ("bgbgg" "jewel" ("bgbgg" "level"))
     ("bbggg" "hotel" ("bgggg" "motel"))
     ("bbbgy" "clued" ("bybgb" "golem") ("byygb" "lumen") ("bgbgy" "olden"))
     ("bggbb" "jetty" ("bggbb" "detox" ("bggbb" "fetch")) ("bgggg" "petty"))
     ("bybgb" "cheek" ("bbggy" "kneed") ("bbggb" "queen"))
     ("bybbg" "dwell" ("bbggg" "quell")) ("bgyyb" "teeth") ("bgygb" "tenet")
     ("bgybb" "depth" ("gggyb" "depot") ("bgbgy" "hefty") ("ygbyb" "teddy")
      ("bgyyb" "tempo") ("bgbgg" "tenth"))
     ("byybb" "eject" ("gbbby" "empty") ("gbgbg" "event") ("bbgbg" "theft"))
     ("bbggb" "octet" ("gbggb" "often") ("ybggy" "totem")) ("bbygg" "towel")
     ("byygb" "tweed" ("ggggb" "tweet"))
     ("bbygb" "comet" ("ggbgg" "covet") ("bbbgg" "duvet") ("bgbgy" "token")
      ("bbggg" "unmet"))
     ("bbbgg" "dowel" ("ygbgg" "model") ("bgbgg" "hovel" ("bgggg" "novel"))
      ("bgggg" "vowel"))
     ("bgbyb" "needy" ("bggbg" "geeky") ("bgggg" "weedy"))
     ("bgbby" "cello" ("bgggg" "hello") ("bgggb" "jelly") ("bgybb" "leggy")
      ("bgyby" "lemon") ("bggby" "felon" ("bgggg" "melon")) ("bgbgb" "newly")
      ("yggbb" "welch"))
     ("bgbbb" "decoy" ("ggbgb" "demon") ("bggyb" "gecko") ("bgbbg" "penny")
      ("bgbgb" "venom") ("bgybb" "wench"))
     ("bybgg" "excel" ("ggbgg" "expel") ("ybbgg" "kneel" ("bbggg" "wheel")))
     ("bybby" "elegy" ("bggbb" "fleck") ("bygbb" "whelp"))
     ("bbbgb" "women" ("bgbgg" "coven" ("bgbgg" "dozen"))
      ("bgbgb" "covey" ("bgbgg" "dopey" ("bgbgg" "gooey"))) ("bgbgy" "honey")
      ("bbggg" "hymen") ("bgygb" "modem") ("bgygy" "money") ("bbbgy" "unfed")
      ("ybbgy" "unwed") ("ggbgg" "woken" ("ggbgg" "woven"))))
    ("yybbb" "acorn" ("ggyyb" "actor") ("gbggg" "adorn")
     ("gbggb" "abort" ("gbggb" "agora")) ("gbbgy" "angry") ("gbyyg" "apron")
     ("gbgyb" "aroma")
     ("gbyyb" "abhor" ("gbbyy" "aorta") ("gybgg" "arbor")
      ("gbbgg" "ardor" ("ggbgg" "armor")) ("gbbgy" "arrow"))
     ("gbbyb" "altar" ("gbbgy" "array") ("gbbbg" "augur"))
     ("gbbgb" "alarm" ("gbggb" "apart" ("gbggb" "award"))) ("ybgyb" "broad")
     ("yybgb" "chard" ("ggggb" "charm" ("ggggb" "chart"))) ("yyygb" "cobra")
     ("yyyyb" "coral") ("yybyy" "crank") ("yygyb" "croak") ("ybggb" "flora")
     ("ybgyg" "groan") ("ybyyg" "organ")
     ("ybygb" "board" ("bgggg" "hoard") ("byggb" "ovary"))
     ("ybyyb" "molar" ("bybyy" "bravo") ("bgbgy" "borax" ("bgggb" "foray"))
      ("ggygy" "moral") ("bgggg" "polar"))
     ("ybbyy" "grand" ("bgggg" "brand") ("bgggy" "drank") ("ggggb" "grant")
      ("byyyb" "lunar") ("bgggb" "frank" ("bgggg" "prank")))
     ("ybbyg" "brawn" ("bgggg" "drawn" ("bgggg" "prawn")) ("ygybg" "urban"))
     ("ybbgb" "quart" ("bgggb" "guard") ("ggggb" "quark") ("byygy" "ultra")
      ("byygb" "umbra") ("bbggb" "dwarf" ("byggg" "wharf")))
     ("yybyb" "track" ("yggyb" "craft")
      ("bggyb" "cramp" ("gggbb" "crawl" ("gggbb" "crazy"))) ("ggggb" "tract")
      ("bgggg" "crack" ("bgggg" "wrack")))
     ("ybbyb" "draft" ("gggbb" "drama" ("gggbb" "drawl")) ("yggyb" "fraud")
      ("bgggg" "graft") ("bggbb" "graph" ("bggbb" "brawl") ("gggbb" "gravy"))
      ("byybb" "mural") ("bggby" "tramp" ("gggbb" "trawl") ("yggbb" "wrath"))))
    ("ybbby" "outer" ("bbgyy" "entry") ("ybbyg" "decor" ("bybgg" "error"))
     ("byyyy" "erupt") ("bbygg" "ether") ("bybgy" "cruel" ("bgggg" "gruel"))
     ("ybbyy" "credo" ("byyby" "heron"))
     ("bybyg" "demur" ("bgggg" "femur" ("bgggg" "lemur")))
     ("bbggg" "deter" ("byggg" "enter") ("bgggg" "meter")) ("ybgyy" "metro")
     ("bbbgg" "fever" ("ygbgg" "defer")
      ("bybgg" "elder" ("ybbgg" "cheer") ("gbbgg" "ember")) ("ggbgg" "fewer")
      ("gbbgg" "flyer") ("gybgg" "freer")
      ("bbbgg" "cyber" ("bybgg" "dryer") ("bgbgg" "hyper"))
      ("bgggg" "lever" ("bgggg" "never")) ("bgbgg" "leper" ("bgbgg" "newer")))
     ("gbygg" "other") ("gbggg" "otter") ("gbyyy" "overt")
     ("gbbgg" "odder" ("gbggg" "older" ("gbggg" "order"))
      ("gbbgg" "offer" ("gbbgg" "owner")))
     ("bbbgy" "creed" ("ggggb" "creek" ("ggggb" "creep"))
      ("bgggg" "breed" ("bgggg" "freed" ("bgggg" "greed")))
      ("bgggb" "green" ("bgggg" "preen")))
     ("bgbgg" "buyer" ("bgbgg" "purer" ("bgbgg" "queer"))) ("bgbyy" "query")
     ("ybyyg" "tenor")
     ("bbygy" "beret" ("byggg" "egret") ("byygg" "greet") ("bbggy" "threw"))
     ("ybygg" "tower")
     ("bbyyy" "crept" ("byyby" "berth") ("yggbg" "erect") ("bygbg" "exert")
      ("bggby" "trend"))
     ("byygg" "truer") ("bgygg" "tuber")
     ("bybgg" "udder" ("ybbgg" "bluer") ("gbggg" "under")
      ("gbbgg" "ulcer" ("gbbgg" "upper")))
     ("byggg" "utter") ("ybggg" "voter")
     ("ybbgg" "mower" ("ygbgg" "homer") ("ggbgg" "mover")
      ("bgbgg" "cover" ("ggbgg" "corer") ("bgggg" "hover" ("bgggg" "lover"))
               ("bgbgg" "joker" ("bgbgg" "boxer" ("bgbgg" "foyer" ("bgbgg" "goner")))
                        ("bgggg" "poker")))
      ("bgggg" "cower" ("bgggg" "lower" ("bgggg" "power"))) ("bgygg" "wooer"))
     ("bbbyy" "clerk" ("ybygb" "decry") ("bbggb" "every") ("byggb" "leery")
      ("bbygb" "berry" ("bgggg" "ferry" ("bgggg" "merry")))
      ("bbyyb" "derby" ("yggbg" "nerdy")) ("ybyyb" "mercy" ("bgggb" "perch"))
      ("bbyyy" "jerky" ("bgggg" "perky")) ("ybgyg" "wreck")))
    ("ybbgy" "cress" ("ggggb" "crest") ("bgggg" "dress" ("bgggg" "press"))
     ("byygb" "verso") ("bgggb" "fresh" ("bgggb" "wrest")))
    ("ybgbb" "print" ("yygbb" "chirp") ("yggbb" "crimp") ("bggbg" "drift")
     ("bygbg" "flirt")
     ("bggbb" "grill" ("bggbb" "brick" ("bgggg" "crick")) ("gggbb" "grimy")
      ("bgggg" "drill" ("bgggg" "frill" ("bgggg" "krill"))))
     ("gggbb" "primo" ("gggby" "prior") ("gggbb" "prick" ("gggbb" "privy")))
     ("bggby" "fritz" ("bggyb" "trick")) ("bygby" "third" ("gbggb" "twirl"))
     ("bygbb" "quirk" ("bbggb" "whirl"))
     ("bgggb" "bring" ("ggggb" "brink" ("ggggb" "briny")) ("bgggb" "drink")
      ("bgggy" "grind") ("bgggg" "wring")))
    ("ybggb" "brisk" ("bgggg" "frisk")
     ("bgggb" "crisp" ("bgggy" "prism") ("bgggb" "wrist")))
    ("ybgbg" "tripe" ("bgggg" "gripe")
     ("bggyg" "price" ("gggbg" "pride" ("gggbg" "prime" ("gggbg" "prize"))))
     ("gggbg" "tribe" ("gggbg" "trice" ("gggbg" "trite")))
     ("bggbg" "bride" ("gggbg" "bribe" ("gggbg" "brine")) ("bggyg" "drive")
      ("bggbg" "crime" ("bgggg" "grime") ("bggbg" "urine")))
     ("yggbg" "write"))
    ("ybbbg" "prove" ("bygbg" "chore") ("ygbbg" "crepe")
     ("byybg" "forge" ("gggbg" "force" ("gggbg" "forte")) ("bgggg" "gorge")
      ("bggbg" "borne" ("bggbg" "horde")) ("byybg" "ombre"))
     ("gggbg" "probe" ("gggbg" "prone")) ("ggbbg" "prude" ("gggbg" "prune"))
     ("gybbg" "puree" ("gggbg" "purge")) ("yggbg" "grope" ("bgggg" "trope"))
     ("bgggg" "drove" ("bgggg" "grove" ("bgggg" "trove")))
     ("bgbbg" "brute" ("bgbbg" "creme") ("bggbg" "crude") ("bggyg" "truce"))
     ("bybyg" "verge") ("bybgg" "nerve" ("bbggg" "curve") ("bgggg" "verve"))
     ("bybbg" "there" ("bbygg" "genre") ("bbyyg" "merge") ("ggyyg" "three")
      ("bgggg" "where"))
     ("bggbg" "drone" ("bgggg" "crone") ("yggbg" "erode")
      ("bggbg" "broke" ("bggbg" "froze" ("bggbg" "wrote")))))
    ("ybbbb" "truly" ("bygyb" "blurb") ("yygyb" "blurt") ("yyybb" "burnt")
     ("yygbb" "court") ("ygbby" "crypt") ("byygg" "burly" ("bgggg" "curly"))
     ("bgbgb" "droll") ("bybyb" "color" ("byygg" "floor")) ("yybbg" "forty")
     ("ygbbb" "broth" ("bggyb" "front") ("bgggg" "froth")) ("ygybb" "grout")
     ("yggbb" "brunt" ("bgggg" "grunt")) ("bybyg" "glory" ("byygg" "lorry"))
     ("byyyb" "flour" ("bybyy" "lurch"))
     ("bygbb" "churn" ("bbggb" "gourd") ("bbggg" "mourn"))
     ("byybg" "curry" ("gggbg" "curvy") ("bgggg" "furry" ("bgggg" "hurry"))
      ("bggbg" "murky"))
     ("bybby" "hydro" ("ygbgb" "myrrh"))
     ("byybb" "forum" ("gygyb" "furor") ("byyyy" "humor") ("bygyb" "juror")
      ("byygb" "occur"))
     ("bybbb" "morph" ("byyby" "chord") ("bgybb" "donor") ("byybb" "fjord")
      ("bggbb" "forgo") ("bgyby" "honor") ("gggbb" "moron") ("bggyg" "porch"))
     ("bgybb" "croup" ("bgggg" "group") ("bgggy" "proud"))
     ("bgbyb" "growl" ("bggbg" "drool") ("bgggg" "prowl"))
     ("bgbbg" "crony" ("bggbg" "proxy"))
     ("gybbb" "throb" ("ggyyb" "thorn") ("ggggb" "throw") ("gygyb" "torch"))
     ("ggbgb" "troll") ("ggbbb" "troop") ("ggybb" "trout")
     ("gggbb" "truck" ("gggbg" "trunk") ("gggbb" "trump" ("gggbb" "truth")))
     ("gyybb" "thrum" ("gbyyy" "tumor") ("gbgyb" "turbo") ("gbyyb" "tutor"))
     ("bybgb" "world")
     ("bybbg" "corny" ("bgybg" "dowry") ("bgggg" "horny")
      ("bggbg" "wordy" ("gggbg" "worry")))
     ("yybbb" "forth" ("bgyyb" "motor") ("bgggg" "north" ("bgggg" "worth")))
     ("bgbbb" "crowd" ("gggbb" "crock" ("gggbg" "crook")) ("ggggb" "crown")
      ("bggby" "droop") ("bgggy" "drown") ("yggbb" "frock")
      ("bggbg" "brood" ("bggbg" "frond"))
      ("bgggb" "brown" ("bgggg" "frown" ("bgggg" "grown")))
      ("bggbb" "broom" ("ggggb" "brook") ("bgggg" "groom") ("bggbb" "prong")
               ("bgggb" "proof"))
      ("bggyb" "wrong"))
     ("bggbb" "wrung" ("bggbb" "crumb" ("ggggb" "crump")) ("bgggb" "drunk")
      ("bggby" "gruff"))
     ("bgbgg" "dryly" ("bgggg" "wryly")))
    ("bgbbb" "tangy" ("bgbgg" "baggy")
     ("bggbb" "banal" ("gggbb" "banjo") ("bgggg" "canal") ("bggbb" "canon"))
     ("ygbyb" "gamut") ("ygyyb" "gaunt")
     ("bgbyg" "gaudy" ("ggbbg" "gawky" ("ggbbg" "gayly")))
     ("bgbby" "bayou" ("bggbb" "kayak")) ("bgbgb" "laugh")
     ("bgbyb" "gamma" ("ygygg" "magma")) ("bgggb" "manga" ("ggggb" "mango"))
     ("bgggg" "mangy")
     ("bggbg" "candy" ("gggbg" "canny") ("yggbg" "fancy")
      ("bgggg" "dandy" ("bgggg" "handy"))
      ("bggbg" "fanny" ("bggbg" "lanky" ("yggbg" "manly")) ("bgggg" "nanny")))
     ("bgybb" "fauna" ("bgbyb" "bacon") ("bgbyy" "naval"))
     ("bgbbb" "macaw" ("bgygb" "cabal") ("bgggb" "cacao")
      ("bgybb" "caulk" ("ygbbb" "havoc")) ("bgbyb" "kappa") ("gggbb" "macho")
      ("ggbgb" "madam") ("ggbbb" "mambo") ("ggbyb" "mamma") ("bgbgb" "papal"))
     ("ygbbg" "batty" ("bgggg" "catty" ("bgggg" "fatty" ("bgggg" "patty"))))
     ("ggbbb" "taboo") ("ggggb" "tango")
     ("ggbbg" "tabby"
      ("ggbbg" "tacky" ("ggbbg" "taffy" ("ggbbg" "tally" ("ggbbg" "tatty")))))
     ("ggybb" "talon" ("ggbby" "taunt")) ("ggybg" "tawny")
     ("ygybb" "daunt" ("bgbyy" "baton" ("bggby" "natal"))
      ("bgggg" "haunt" ("bgggg" "jaunt" ("bgggg" "vaunt"))))
     ("bgbbg" "bawdy" ("ggbyg" "badly") ("ggbbg" "balmy") ("ygbbg" "cabby")
      ("bgbyg" "dally" ("ygbgg" "madly"))
      ("bgbbg" "happy" ("bgbbg" "jazzy" ("bgbbg" "mammy")))
      ("bgbgg" "caddy" ("bgggg" "daddy" ("bgggg" "paddy"))) ("bgybg" "wacky"))
     ("bgyyb" "pagan" ("bggbg" "wagon"))
     ("ygbbb" "caput" ("ggbby" "catch") ("bgbgy" "datum") ("ygyby" "patch")
      ("bgbyg" "fault" ("bgggg" "vault")) ("bgbby" "fatal" ("bgyby" "waltz"))
      ("ygbby" "batch"
               ("bgggg" "hatch" ("bgggg" "latch" ("bgggg" "match" ("bgggg" "watch"))))))
     ("ygbby" "yacht"))
    ("bybgy" "beast" ("bgggb" "leash")
     ("bgggg" "feast" ("bgggg" "least" ("bgggg" "yeast"))))
    ("bbyby" "widen" ("byyyy" "denim") ("bgygb" "dicey")
     ("bybyg" "begin" ("bybgg" "elfin")) ("bgyyy" "fiend")
     ("bybyb" "befit" ("bybgb" "equip") ("bybgy" "ethic") ("bgbgb" "helix"))
     ("bybgb" "impel") ("byggy" "index") ("bybyy" "ennui" ("ygbby" "inept"))
     ("bybgy" "inlet") ("bygyb" "medic") ("bgbyb" "eight" ("ygbby" "piety"))
     ("bgbgy" "piney")
     ("bgbgb" "bicep" ("bgbgb" "filet") ("ygbgb" "libel") ("bgbgy" "pixel"))
     ("byyyb" "fetid" ("bgygy" "debit") ("bgbgy" "devil") ("bgygg" "tepid"))
     ("bgggb" "video")
     ("bgbgg" "given" ("bgbgg" "liken" ("ggbgg" "linen")) ("bgygg" "vixen"))
     ("ggyyb" "wield") ("bgyyb" "field" ("bgggg" "yield")))
    ("bbbbb" "could" ("gybbb" "chock")
     ("gbgbb" "chuck" ("gggbb" "chump") ("gggbg" "chunk")) ("gyyyg" "cloud")
     ("gyyyb" "clout") ("gybyb" "clock" ("gggbb" "cloth" ("gggbb" "clown")))
     ("gbgyb" "cluck" ("gggbb" "clump" ("gggbb" "clung"))) ("ggbyb" "colon")
     ("ggbbb" "comfy" ("ggbbb" "conch")) ("ggbby" "condo")
     ("gggbb" "couch" ("gggbg" "cough") ("gggbb" "count")) ("ggbgb" "coyly")
     ("bgyby" "donut") ("bggby" "doubt" ("gggbb" "dough")) ("bbygy" "dully")
     ("ybyby" "duchy" ("ggyyb" "dutch")) ("yybyb" "block" ("bgggg" "flock"))
     ("bybyg" "blond" ("gggbg" "blood") ("bggbg" "flood"))
     ("byyyb" "flout" ("byggb" "ghoul")) ("bgbgy" "dolly" ("ygbgg" "godly"))
     ("bbygb" "bully" ("bgggg" "fully" ("bgggg" "gully"))) ("yybbb" "knock")
     ("bybgb" "knoll") ("bbbyb" "glyph" ("byygg" "lymph")) ("ybbyb" "lynch")
     ("bgyyb" "mogul") ("bgbyy" "moldy") ("bgggb" "moult")
     ("ybyyb" "gulch" ("bgyyb" "lucky") ("bgygg" "lunch") ("bgggg" "mulch"))
     ("bybyb" "bloom" ("gggbb" "blown") ("bggbb" "flown") ("bgggg" "gloom")
      ("bybgb" "nylon"))
     ("bybgy" "oddly") ("byyby" "outdo") ("ybgyb" "pluck")
     ("bbgyb" "flunk" ("yggbb" "bluff") ("bgggb" "blunt") ("gggbb" "fluff")
      ("ggggb" "flung") ("bggbb" "plumb" ("ggggb" "plump")) ("bgggg" "plunk"))
     ("bgbyb" "lobby" ("ggbbg" "lofty" ("ggbbg" "loopy")) ("ygbby" "polyp"))
     ("ygbbb" "botch" ("bgggg" "notch") ("bgbgg" "pooch"))
     ("bbyby" "dumpy" ("ygbbg" "buddy") ("gggbg" "dummy") ("ygybg" "muddy")
      ("ygbyg" "pudgy"))
     ("bbyyb" "bulky" ("bgybg" "lumpy") ("bggbg" "pulpy"))
     ("bbybb" "humph" ("ggbbb" "hunky") ("bgggb" "jumpy")
      ("bggbb" "gummy" ("bgggg" "mummy"))
      ("bgbbb" "bunny" ("ggbbg" "buggy") ("bggbg" "funky") ("bgggg" "funny")
               ("bgbbg" "fuzzy") ("bgybg" "nutty"))
      ("bgbgb" "guppy" ("bgggg" "puppy")) ("bgbyb" "puffy" ("ggbbg" "putty")))
     ("bbbbb" "nymph" ("bgyyb" "pygmy"))
     ("byybb" "gumbo" ("bgyyy" "buxom") ("bgggg" "jumbo") ("bgbbg" "junto")
      ("ygbby" "ought") ("ygbbg" "outgo") ("bgbby" "quoth"))
     ("bbgbb" "thumb" ("ggggb" "thump"))
     ("ybybb" "bunch" ("ggbgg" "butch") ("bgbgg" "hutch") ("bgbyb" "mucky")
      ("bgggg" "hunch" ("bgggg" "munch" ("bgggg" "punch"))) ("byyyb" "uncut"))
     ("yggbb" "pouch" ("bgggg" "touch" ("bgggg" "vouch")))
     ("bybbb" "phony" ("bbgyb" "known") ("gggbb" "photo") ("bgggb" "thong")
      ("yggbb" "whoop"))
     ("bgbby" "dowdy" ("ggbyg" "dodgy") ("gggbg" "downy") ("bgggg" "howdy")
      ("bgbgg" "goody" ("bgggg" "moody")) ("ygbgg" "toddy") ("bgygg" "woody"))
     ("bgbgb" "holly" ("ggbgg" "hotly")
      ("bgggg" "folly" ("bgggg" "golly" ("bgggg" "jolly"))) ("bgygg" "lowly")
      ("bgbgg" "nobly" ("bgbgg" "wooly")))
     ("bgbbb" "boozy" ("ggbbg" "bobby") ("ggybb" "bongo") ("gggbb" "booth")
      ("gggbg" "booby" ("gggbg" "booty")) ("bggbg" "goofy") ("ygbbg" "hobby")
      ("bgbbb" "month") ("bgybb" "motto") ("bgbbg" "foggy" ("bgbbg" "poppy"))
      ("bggbb" "tooth") ("bgggg" "woozy"))
     ("bgggg" "would")
     ("bggbg" "bound"
      ("bgggg" "found"
               ("bgggg" "hound" ("bgggg" "mound" ("bgggg" "pound" ("bgggg" "wound"))))))
     ("bggbb" "mouth" ("bggbg" "bough") ("gggyb" "mount") ("bgggb" "pouty")
      ("bggyg" "tough") ("bggbb" "young") ("bgggg" "youth")))
    ("yybby" "tread" ("bggyb" "arena") ("yygyb" "alert" ("gbggg" "avert"))
     ("byggb" "clear") ("byygy" "cedar" ("bgygg" "debar"))
     ("bgggg" "bread" ("bgggg" "dread")) ("bgggy" "dream") ("byygb" "feral")
     ("ygggb" "great") ("byyyg" "beard" ("bgggg" "heard"))
     ("yyyyb" "after" ("gbggg" "alter") ("ybgyy" "extra") ("ybyyy" "heart"))
     ("bygyb" "opera") ("gyyyb" "teary" ("ggygb" "terra")) ("ggggb" "treat")
     ("bgggb" "break" ("bgggb" "cream")
      ("bgggg" "creak" ("bgggg" "freak" ("bgggg" "wreak"))))
     ("byyyb" "learn" ("byyyb" "amber") ("byyyy" "anger") ("ygggb" "pearl")
      ("bgggb" "weary") ("bgggg" "yearn") ("bgygb" "zebra")))
    ("bbbyy" "spelt" ("ybybb" "bused" ("bbggb" "nosey")) ("yyybb" "pesky")
     ("yyyby" "pesto") ("gyyby" "setup") ("gbybb" "semen" ("ggbgg" "seven"))
     ("gbgbb" "seedy" ("gygbb" "sheen")) ("gbgyb" "sleek") ("gygyb" "sleep")
     ("gbgyg" "sleet") ("gygyg" "slept") ("gbggg" "smelt") ("ggggb" "spell")
     ("gggbb" "speed" ("gggbb" "speck") ("gggbg" "spend")) ("gggbg" "spent")
     ("gbgby" "steed") ("gbgyy" "steel") ("gygby" "steep")
     ("gygbb" "sheep" ("gbggg" "sweep"))
     ("gbgbg" "sheet" ("gbgbg" "scent") ("gbggg" "sweet"))
     ("gbggb" "shelf" ("ggggb" "shell") ("gbggb" "smell" ("gbggg" "swell")))
     ("gygbg" "swept") ("ybybg" "onset" ("bbggg" "beset") ("bgggg" "unset"))
     ("ygybg" "upset")
     ("ybyby" "testy" ("yyybb" "ethos") ("ygybb" "fetus") ("bgggg" "zesty")))
    ("bybbb" "cloak" ("bgbgb" "allay")
     ("bgyyb" "allot" ("ggggb" "allow" ("ggggb" "alloy")))
     ("bggyb" "aloft" ("gggyb" "aloof") ("gggbb" "along" ("gggbb" "aloud")))
     ("bygyb" "afoul" ("gbgbg" "atoll")) ("gybyg" "chalk")
     ("gbbyb" "chaff" ("gggbb" "champ" ("gggbb" "chant")))
     ("ggbyb" "clamp" ("gggbb" "clang")) ("ggbyg" "clack" ("gggbg" "clank"))
     ("gbyyb" "coach" ("ggyyb" "cocoa") ("ggybb" "comma"))
     ("ygbyg" "black" ("bgggg" "flack")) ("bgbyy" "flaky")
     ("bgggb" "bloat" ("bgggg" "float" ("bgggg" "gloat"))) ("bbbgb" "human")
     ("byyyb" "loamy" ("yyybb" "aglow") ("gggbb" "loath")) ("ybyyb" "mocha")
     ("bgbyg" "blank" ("bgggg" "flank" ("bgggg" "plank")))
     ("bgbyb" "alpha" ("ggbbb" "album") ("ygbbb" "bland" ("bgggg" "gland"))
      ("ygbbg" "llama") ("ygybb" "plant") ("ygybg" "plaza"))
     ("byyyy" "koala" ("ygbyg" "polka"))
     ("bybyb" "amply" ("gbbgb" "adult") ("gbggg" "apply") ("gbygg" "aptly")
      ("gbbyb" "annul" ("gbbgg" "awful")) ("yybgb" "qualm"))
     ("bbgyb" "about" ("gbgbg" "adopt" ("gbgbg" "afoot"))
      ("gbgbb" "agony" ("gyggb" "among")) ("ybgyy" "quota"))
     ("bbbyg" "thank")
     ("bbyyb" "annoy" ("gbbgb" "abbot") ("ybbyb" "dogma") ("ybbyg" "foamy")
      ("ybgyb" "tonga"))
     ("bybgb" "bylaw" ("bbygb" "pupal") ("ybygb" "tubal"))
     ("bbbyb" "adapt" ("gbbby" "aunty") ("ybgbb" "guava") ("ybbby" "junta")
      ("bbgby" "twang"))
     ("yyygb" "focal" ("byygg" "octal") ("bgggg" "local" ("bgggg" "vocal")))
     ("bbyyy" "vodka")
     ("ybbyg" "aback" ("bbggg" "knack" ("bbggg" "quack" ("bbggg" "whack"))))
     ("bbygb" "gonad" ("bgygg" "nomad") ("bgbgy" "today") ("bgbgb" "topaz")
      ("bgygb" "woman"))
     ("byygb" "tonal" ("bgbgg" "loyal" ("bgbgg" "modal")) ("bybgg" "offal")
      ("ggbgg" "total") ("bgggg" "zonal")))))

(defun precompute-guesser-tree (words guesser)
  (let* ((guess (funcall guesser words))
         (words (remove guess words :test #'string=)))
    (list* guess
           (loop :for score :in (remove-duplicates (loop :for w :in words
                                                      :collect (score-guess guess w))
                                                   :test #'string=)
              :for remaining := (filter words (list guess score))
              :when remaining
              :collect (list* score (precompute-guesser-tree remaining guesser))))))

(defun prune-guess-tree (tree score)
  (rest (assoc score (rest tree) :test #'string=)))

(defun make-guess-tree-iterator (&optional (tree *precomputed-tree*))
  (let ((cur tree))
    (lambda (&optional (result "ggggg"))
      (cond
        ((string= result "ggggg")
         (setq cur tree))
        (t
         (setq cur (prune-guess-tree cur result))))
      (first cur))))
