(in-package :wordle-solve)

;;;
;;; This tree was computed using the #'GREEDY-GUESS guesser
;;; and the published list of possible wordle answers.
;;;
(defvar *precomputed-tree*
  '("raise" ("yygbg" "afire") ("byyyg" "aisle") ("yyggg" "arise")
    ("bygyg" "aside") ("byggb" "amiss")
    ("bygbg" "alike" ("gggbg" "alive") ("gygbg" "agile")
     ("gbgbg" "abide" ("gbgbg" "anime")))
    ("bygby" "alien") ("yyybg" "irate") ("ygbgb" "harsh" ("bgggg" "marsh"))
    ("ygbgg" "parse") ("byygb" "quasi") ("gggbb" "rainy")
    ("ggybb" "rabid" ("gggyb" "rabbi") ("ggbgy" "radii" ("ggggb" "radio"))
     ("ggbgg" "rapid") ("ggbgb" "ratio"))
    ("ggbyb" "raspy") ("ggbbg" "range")
    ("ggbby" "racer" ("ggbgb" "ramen" ("ggbgg" "raven")) ("ggbgg" "rarer"))
    ("ggbbb" "randy" ("ggbyb" "radar") ("gggbb" "ranch")
     ("ggbbg" "rally" ("ggbbg" "ratty")) ("ggyby" "rayon")
     ("ggbbb" "rajah" ("ggbbg" "ralph") ("ggbbb" "razor")))
    ("gbgby" "reign")
    ("gybby" "relay" ("ggbyg" "ready") ("ggyyb" "realm")
     ("ggbyb" "reach" ("ggggb" "react") ("gggbb" "rearm")) ("ggggb" "relax")
     ("ggygb" "regal" ("ggbgg" "renal")) ("ggbgg" "repay")
     ("ggbgb" "rebar" ("ggygb" "rehab") ("ggbgb" "recap")))
    ("gbybg" "ridge" ("ggbbg" "rifle")) ("gbygg" "rinse")
    ("gbyyy" "resin" ("gygyg" "risen") ("gygyb" "riser"))
    ("gbyby" "riper" ("gybyb" "refit" ("ggbgg" "remit") ("ggbgb" "relic"))
     ("ggggb" "ripen") ("ggbgg" "rider" ("ggbgg" "river")) ("ggbgb" "rivet"))
    ("gyybb" "rival") ("gybgb" "roast") ("gbyyb" "risky")
    ("gbbgg" "reuse" ("gbggg" "rouse")) ("gbbgb" "roost") ("gbgbb" "rhino")
    ("gbbbg" "rogue" ("gbbgg" "revue") ("gbbbg" "rhyme") ("ggyyg" "rouge")
     ("ggbyg" "route") ("gbbyg" "rupee"))
    ("gybbb" "royal" ("ggbyb" "roach") ("gbbyb" "rumba") ("gbbgg" "rural"))
    ("gbybb" "robin" ("gbbgb" "rigid") ("gybyb" "rigor") ("gbbyb" "right"))
    ("gbbbb" "ruddy" ("gbbbg" "rocky" ("ggbbg" "roomy")) ("gyybb" "round")
     ("gybbb" "rough") ("gbbgg" "rowdy") ("gbbbb" "robot" ("ggbgy" "rotor"))
     ("ggbbb" "rumor") ("ggbbg" "rugby"))
    ("gbbby" "ruler" ("gybyg" "recur") ("gbyyb" "reply") ("gybyy" "rerun")
     ("gbbyy" "retro" ("ggggb" "retry")) ("gbbyb" "reedy" ("ggbbb" "retch"))
     ("gybyb" "rebut" ("ggbgg" "recut"))
     ("gbygb" "rebel" ("ggbgg" "repel" ("ggbgg" "revel")))
     ("gbbgg" "roger" ("gbbgg" "refer") ("ggbgg" "rover" ("ggbgg" "rower")))
     ("ggbgg" "ruder") ("gbbgb" "renew" ("gbbgb" "rodeo")))
    ("gbbyy" "rebus" ("ggbby" "reset")) ("gbbyb" "rusty")
    ("bbggg" "noise" ("bgggg" "poise") ("bbggg" "guise"))
    ("bbggy" "exist" ("ybggg" "heist")) ("byyyy" "sepia")
    ("bbyyg" "siege" ("yybbg" "issue") ("gggbg" "sieve") ("ggbgg" "singe")
     ("ggbbg" "since"))
    ("ybgyg" "shire" ("gbggg" "spire")) ("yyyyb" "stair")
    ("bbgyg" "slipe" ("gggbg" "slice" ("gggbg" "slide" ("gggbg" "slime")))
     ("gbgyg" "spice" ("gggbg" "spike" ("gggbg" "spine" ("gggbg" "spite"))))
     ("gygbg" "smile") ("gbggg" "snipe")
     ("gbgbg" "seine" ("gggbg" "seize") ("gbgyg" "snide")
      ("gbggg" "shine" ("gbggg" "swine")) ("gbgbg" "smite" ("gbggg" "suite"))))
    ("ybbyg" "scree" ("ggybg" "score") ("gbgyg" "serve") ("gbggg" "spree")
     ("gbgbg" "surge")
     ("gbybg" "shore"
      ("gbggg" "snore" ("gbggg" "spore" ("gbggg" "store" ("gbggg" "swore"))))))
    ("bgbgb" "salsa" ("ygygb" "lasso") ("bgggb" "palsy") ("ggbgb" "sassy")
     ("bgbgb" "pansy" ("ggbgg" "patsy")) ("ygbgb" "gassy"))
    ("ybybg" "dirge" ("bygbg" "eerie") ("bgybg" "fibre"))
    ("bybgb" "slash" ("bbygb" "angst") ("ybygb" "abyss") ("bbggy" "chasm")
     ("ygggb" "class" ("bgggg" "glass")) ("bgggg" "clash" ("bgggg" "flash"))
     ("bgggb" "clast" ("bgggg" "blast") ("ggggb" "clasp") ("bgggb" "flask"))
     ("bbggg" "awash" ("bbggg" "gnash" ("bbggg" "quash"))) ("ybggb" "amass")
     ("gbggb" "spasm") ("gbggg" "smash" ("gbggg" "stash" ("gbggg" "swash")))
     ("bbggb" "boast" ("bgggg" "coast" ("bgggg" "toast"))))
    ("ybygb" "first")
    ("yybgb" "brash" ("bgygb" "artsy") ("ggggb" "brass")
     ("bgggg" "crash" ("bgggg" "trash"))
     ("bgggb" "crass" ("bgggb" "grasp") ("bgggg" "grass")))
    ("bbygb" "missy" ("bgbgb" "kiosk") ("ggbgb" "midst") ("bgggg" "sissy")
     ("bgbgg" "gipsy" ("bgggg" "tipsy")))
    ("bybgg" "cease" ("bbygg" "abuse" ("gbggg" "amuse")) ("gbggg" "chase")
     ("bgggg" "lease" ("bgggg" "tease")) ("bbggg" "abase" ("bbggg" "phase")))
    ("yyyby" "aider") ("yybgg" "arose" ("ygbgg" "erase"))
    ("yybbg" "grace" ("yyybg" "agree") ("ygybg" "argue")
     ("bggyg" "crane" ("gggbg" "crate" ("gggbg" "crave" ("gggbg" "craze"))))
     ("gygbg" "glare")
     ("gggbg" "grade"
      ("gggbg" "grape" ("gggbg" "grate" ("gggbg" "grave" ("gggbg" "graze")))))
     ("byybg" "adore" ("gbbgg" "azure"))
     ("bygbg" "blare" ("bgggg" "flare") ("bbggg" "aware"))
     ("bgggg" "brace" ("bgggg" "trace"))
     ("bggbg" "drake" ("bgggg" "brake") ("gggbg" "drape") ("yggbg" "trade")
      ("bggbg" "brave" ("bggbg" "frame"))))
    ("yygbb" "briar" ("bgggg" "friar") ("bgggb" "triad" ("ggggb" "trial")))
    ("yybyg" "scare"
     ("gbggg" "share" ("gbggg" "snare" ("gbggg" "spare" ("gbggg" "stare")))))
    ("bybyg" "slate" ("gggbg" "slave") ("gygyg" "stale")
     ("gbggg" "skate" ("gbggg" "state"))
     ("gbgyg" "stage" ("gggbg" "stake" ("gggbg" "stave")))
     ("gbgbg" "shape"
      ("gggbg" "shade" ("gggbg" "shake" ("gggbg" "shame" ("gggbg" "shave"))))
      ("gbgyg" "space" ("gggbg" "spade")) ("gbgbg" "snake" ("gbgbg" "suave")))
     ("gygbg" "scale" ("gbggg" "shale")) ("ybgbg" "usage"))
    ("bbbyg" "stone" ("gbggg" "scone" ("gbggg" "shone")) ("gbbgg" "scene")
     ("gygbg" "smote") ("gbybg" "solve")
     ("gbgbg" "scope" ("gbggg" "slope") ("gbgbg" "shove" ("gbgbg" "smoke"))
      ("gbgyg" "spoke"))
     ("gggbg" "stoke" ("gggbg" "stole" ("gggbg" "stove"))) ("ggbbg" "style")
     ("gbbbg" "segue") ("ybbyg" "ensue"))
    ("bgbgg" "lapse" ("bgygg" "pause") ("bgbgg" "cause" ("bgbgg" "masse"))
     ("ygbgg" "false"))
    ("ygybb" "nadir" ("bgbgg" "tapir"))
    ("ygbbg" "carle" ("gggbg" "carve") ("yggbg" "farce") ("bggyg" "large")
     ("bggbg" "barge"))
    ("byybg" "image" ("gbgbg" "inane"))
    ("bygbb" "align" ("gggbb" "alibi") ("gygbb" "axial")
     ("gbgyy" "aging" ("gbggg" "aping")) ("gbgbg" "avian" ("gbgbg" "axion"))
     ("gbgbb" "amity" ("gygbb" "axiom")) ("yggbb" "iliac") ("ybgby" "china")
     ("yygbb" "voila"))
    ("bgbbg" "gable" ("ygybg" "badge") ("ygbgg" "eagle")
     ("ggbbg" "gauge" ("ggbbg" "gaffe") ("gggbg" "gauze"))
     ("bgybg" "bathe" ("ygbbg" "maybe")) ("bgbgg" "ladle" ("bgbgg" "maple"))
     ("bgggg" "cable" ("bgggg" "fable" ("bgggg" "table")))
     ("ygbbg" "mange" ("bgbyg" "vague"))
     ("bgbyg" "halve" ("ygybg" "lathe") ("bgybg" "lance" ("ggbbg" "latte"))
      ("bggyg" "value") ("bgggg" "valve"))
     ("bgbbg" "cache" ("ggbbg" "canoe") ("ygbbg" "dance") ("bgbyg" "haute")
      ("bgbbg" "mauve" ("bgbbg" "payee"))))
    ("bgggb" "daisy" ("bgggb" "waist")) ("bggyb" "saint")
    ("bggbg" "naive" ("bggbg" "maize") ("bgggg" "waive"))
    ("ygbyy" "safer" ("ggbgg" "saner"))
    ("bgbyg" "caste" ("bgybg" "salve") ("ygybg" "sauce") ("bgygg" "saute")
     ("bgggg" "baste"
      ("bgggg" "haste" ("bgggg" "paste" ("bgggg" "taste" ("bgggg" "waste"))))))
    ("bbgby" "teind" ("bggyy" "deign") ("yggby" "deity") ("yygby" "edict")
     ("bygby" "edify") ("byggb" "eking" ("gbggg" "eying")) ("bygbb" "chief")
     ("bggyb" "feign" ("bgggy" "neigh")) ("bygbg" "plied")
     ("yygbb" "evict" ("ybgbg" "quiet")) ("gygbb" "thief") ("bgggb" "being")
     ("bggbb" "weigh"))
    ("bbggb" "hoist" ("bgggg" "foist" ("bgggg" "joist" ("bgggg" "moist")))
     ("bgggb" "noisy") ("bbggb" "bliss") ("bbggg" "twist")
     ("ybggb" "swish" ("byggy" "whisk")))
    ("bbgbg" "toile" ("ybgyg" "elite") ("bbgyg" "elide" ("bgggg" "glide"))
     ("bygyg" "olive") ("bygbg" "opine" ("gbggg" "ovine") ("gbgbg" "oxide"))
     ("gbgbg" "twice" ("gggbg" "twine")) ("ybggg" "utile") ("bggbg" "voice")
     ("bbggg" "exile" ("bbggg" "guile" ("bbggg" "while")))
     ("bbgbg" "chide" ("gggbg" "chime") ("bbggg" "guide") ("ybgbg" "juice")
      ("bbgbg" "knife") ("bggbg" "whine"))
     ("ybgbg" "quite" ("byggg" "unite") ("bbggg" "white")))
    ("bbgyb" "skint" ("gggbb" "skiff" ("gggbb" "skill" ("gggbb" "skimp")))
     ("gbgyb" "scion" ("gbgby" "sniff")) ("gygbb" "slick" ("gbgby" "spiky"))
     ("gygby" "stick") ("gbggy" "sting") ("gyggy" "stink") ("gbggg" "stint")
     ("gbgbg" "shift" ("gbgbg" "spilt" ("gbggg" "stilt")) ("gbggg" "swift"))
     ("gbgbb" "spicy" ("gbgbg" "slimy") ("gggbb" "spill") ("gbgbb" "swill"))
     ("gbggb" "sling" ("gbggb" "shiny" ("gbggg" "spiny"))
      ("gbggg" "suing" ("gbggg" "swing")))
     ("gyggb" "slink") ("gbgby" "stiff" ("gggbb" "still") ("gygbb" "smith"))
     ("ybggb" "using"))
    ("bbgbb" "cling" ("gygbb" "child" ("ggggb" "chili" ("ggggb" "chill")))
     ("gbgbb" "chick") ("ggggb" "clink")
     ("gggbb" "click" ("gggbb" "cliff" ("gggbb" "climb"))) ("bgggg" "fling")
     ("bgggy" "glint") ("bygby" "guild" ("ggggb" "guilt")) ("yygbb" "icily")
     ("ybggg" "icing") ("bggbb" "blimp" ("gggbb" "blitz")) ("yggbb" "flick")
     ("byggg" "lying") ("bgggb" "blind" ("ggggb" "blink") ("bgggb" "flint"))
     ("bbgby" "thigh")
     ("bygbb" "built" ("ggggb" "build") ("bgggb" "quill") ("bgggg" "quilt"))
     ("bbgyb" "unify" ("bggbb" "onion") ("gggbb" "union") ("gggbg" "unity"))
     ("bbggg" "doing" ("gbggg" "dying") ("bgggg" "going") ("byggg" "owing")
      ("bbggg" "thing" ("gbggg" "tying") ("bbggg" "vying")))
     ("ybgbb" "quick" ("bgggb" "juicy") ("bbggg" "thick") ("bbggb" "which"))
     ("bbggb" "joint" ("bgggg" "point") ("bbggy" "think") ("bbggb" "whiny"))
     ("bbgbb" "idiot" ("ggggb" "idiom") ("bbgyb" "opium") ("bbgbg" "twixt")
      ("bbgbb" "whiff")))
    ("ybyyy" "miser" ("byyyy" "serif") ("bgygy" "siren") ("bgggg" "wiser"))
    ("byyyb" "slain" ("gyggy" "snail") ("gbggb" "staid") ("gbyyb" "sigma")
     ("gbggg" "stain") ("gbgyb" "swami") ("ybyyb" "vista"))
    ("byybb" "nidal" ("yyyyb" "admin") ("yybyg" "anvil") ("yybgy" "inlay")
     ("byyyb" "aphid" ("gbbgy" "admit") ("gbbgg" "avoid")) ("ggbyb" "ninja")
     ("byyyy" "plaid") ("yybyy" "plain") ("bygyb" "audio" ("ggggb" "audit"))
     ("bybyg" "avail" ("bbggg" "flail" ("bbggg" "quail")))
     ("bybyy" "claim" ("bgggb" "plait")) ("bgggg" "tidal") ("bgbgy" "lilac")
     ("bybyb" "attic" ("gbbgb" "affix") ("gybgb" "await") ("ybbyb" "khaki"))
     ("yybyb" "again" ("gbbgy" "antic") ("bbggg" "chain")) ("ygbgg" "final")
     ("ygbyb" "giant" ("bgggb" "piano")) ("bgbyy" "villa" ("ggbgg" "viola"))
     ("bgbgg" "vital") ("bgbyb" "pizza" ("bgbbg" "tibia")) ("ygbgb" "titan"))
    ("ybbgg" "erose" ("bgggg" "prose")
     ("bybgg" "curse" ("bgggg" "nurse" ("bgggg" "purse")))
     ("yybgg" "terse" ("bgggg" "verse")) ("byygg" "horse" ("bgggg" "worse")))
    ("yybyb" "strap" ("ybyyb" "arson") ("gbggg" "scrap") ("gbyyg" "sharp")
     ("gbggy" "spray") ("ggyyb" "stark" ("ggggb" "start"))
     ("ggggb" "straw" ("ggggb" "stray"))
     ("gbygb" "solar" ("ggbgg" "sonar") ("gbbgg" "sugar")) ("gbyyy" "spark")
     ("gbggb" "scram")
     ("gbyyb" "sharn" ("ggggb" "shard" ("ggggb" "shark")) ("gbggy" "snarl")
      ("gbggb" "scarf" ("ggggb" "scary") ("gbggb" "swarm")))
     ("gyyyb" "smart"))
    ("ybbgy" "cress" ("ggggb" "crest") ("bgggg" "dress" ("bgggg" "press"))
     ("byygb" "verso") ("bgggb" "fresh" ("bgggb" "wrest")))
    ("ybgby" "fried" ("bgggy" "drier") ("gyggb" "flier")
     ("ygggb" "brief" ("bgggg" "grief")) ("byggb" "plier") ("bygyg" "weird")
     ("bgggg" "cried" ("bgggg" "dried" ("bgggg" "pried" ("bgggg" "tried"))))
     ("bgggb" "crier"))
    ("ybgyy" "skier")
    ("ybgbb" "prink" ("bgggg" "brink" ("bgggg" "drink")) ("yggbb" "crimp")
     ("bggby" "krill") ("gggbg" "prick") ("ggggb" "print")
     ("gggbb" "primo" ("gggby" "prior") ("gggbb" "privy")) ("bygbg" "quirk")
     ("bggbb" "drift" ("gggbb" "drill") ("bggyy" "fritz") ("bggyb" "frill")
      ("bggbb" "grill" ("gggbb" "grimy")))
     ("yygbb" "chirp")
     ("bygbb" "flirt" ("bbggy" "third") ("byggy" "twirl") ("byggb" "whirl"))
     ("bggbg" "brick" ("bgggg" "crick" ("bgggg" "trick")))
     ("bgggb" "bring" ("ggggb" "briny") ("bgggy" "grind") ("bgggg" "wring")))
    ("ybggb" "brisk" ("bgggg" "frisk")
     ("bgggb" "crisp" ("bgggy" "prism") ("bgggb" "wrist")))
    ("ybgbg" "tripe" ("bgggg" "gripe")
     ("bggyg" "price" ("gggbg" "pride" ("gggbg" "prime" ("gggbg" "prize"))))
     ("gggbg" "tribe" ("gggbg" "trice" ("gggbg" "trite")))
     ("bggbg" "bride" ("gggbg" "bribe" ("gggbg" "brine")) ("bggyg" "drive")
      ("bggbg" "crime" ("bgggg" "grime") ("bggbg" "urine")))
     ("yggbg" "write"))
    ("ybgyb" "shirk" ("ggggb" "shirt") ("gbggy" "skirt") ("gbggg" "smirk")
     ("gbggb" "swirl"))
    ("ybbbg" "prove" ("ygbbg" "crepe") ("gggbg" "probe" ("gggbg" "prone"))
     ("ggbbg" "prude" ("gggbg" "prune")) ("gybbg" "puree" ("gggbg" "purge"))
     ("byybg" "forge" ("gggbg" "force" ("gggbg" "forte")) ("bgggg" "gorge")
      ("byybg" "ombre") ("bggbg" "borne" ("bggbg" "horde")))
     ("yggbg" "grope" ("bgggg" "trope"))
     ("bgggg" "drove" ("bgggg" "grove" ("bgggg" "trove")))
     ("bgbbg" "brute" ("bggbg" "crude") ("bgbbg" "creme") ("bggyg" "truce"))
     ("bybyg" "verge") ("bybgg" "nerve" ("bbggg" "curve") ("bgggg" "verve"))
     ("bybbg" "there" ("bbygg" "genre") ("bbyyg" "merge") ("ggyyg" "three")
      ("bgggg" "where"))
     ("bygbg" "chore")
     ("bggbg" "drone" ("yggbg" "erode") ("bgggg" "crone")
      ("bggbg" "troke" ("bgggg" "broke") ("bggbg" "froze") ("yggbg" "wrote"))))
    ("ybbgb" "crust" ("bgggb" "brush") ("ggbgb" "cross") ("ggggb" "crush")
     ("bgbgb" "dross" ("bgggg" "gross")) ("bybgy" "torso") ("bgggy" "truss")
     ("bgggg" "trust") ("bgbgg" "frost" ("bgbgg" "tryst")) ("bybgg" "worst")
     ("byygg" "burst"))
    ("bbbgb" "floss" ("ggbgb" "flush") ("gbbgy" "fussy") ("bgggg" "gloss")
     ("byygb" "lousy") ("bbbgb" "gypsy") ("bgbgb" "blush" ("bgggg" "plush"))
     ("bbygb" "joust") ("bgggy" "slosh") ("bgbgy" "slush")
     ("bbygy" "bossy" ("bgggg" "mossy")) ("bbggb" "boost" ("bbggg" "ghost"))
     ("bbbgy" "hussy" ("yyygb" "shush")))
    ("byyby" "email" ("ybyyg" "ideal") ("yyygb" "media"))
    ("ybyby" "diner" ("ggbgg" "diver") ("bgbyy" "fiery") ("yybgg" "idler")
     ("byyyy" "inert") ("byggg" "inner") ("byygg" "infer" ("ggbgg" "inter"))
     ("bgggg" "finer" ("bgggg" "liner" ("bgggg" "miner"))) ("bgygg" "nicer")
     ("bybyg" "their") ("ygbgg" "cider" ("bgggg" "wider"))
     ("bgbgg" "fiver" ("ggbgg" "fiber" ("ggbgg" "filer" ("ggbgg" "fixer")))
      ("bgygg" "viper") ("bgbgg" "tiger" ("ggbgg" "timer") ("bgbgg" "piper"))
      ("bgggg" "giver" ("bgggg" "liver")))
     ("bybyy" "merit" ("bgggb" "peril")))
    ("bgyyb" "nabis" ("ygygy" "basin") ("bgygg" "basis")
     ("bgygy" "basic" ("ggggb" "basil")) ("ygbgy" "satin"))
    ("yggbb" "dairy" ("bgggg" "fairy" ("bgggg" "hairy")) ("bgggb" "cairn"))
    ("ygbbb" "payor" ("ygyby" "harpy") ("bgggg" "mayor") ("ggbby" "parka")
     ("ggyby" "parry" ("gggbg" "party")) ("bgbyy" "cargo" ("ygybg" "macro"))
     ("bgbgy" "carob" ("bgggy" "baron") ("ggggb" "carol") ("bgggb" "tarot"))
     ("bgbgg" "valor" ("ygbgg" "favor") ("bgygg" "labor")
      ("bgbgg" "major" ("ggbgg" "manor")))
     ("ygbgg" "vapor")
     ("bgbby" "karma" ("bggby" "carat") ("bggyb" "march") ("bggbg" "larva"))
     ("bgyby" "harry" ("gggbg" "hardy") ("bgggg" "carry" ("bgggg" "marry"))
      ("bggbg" "tardy" ("yggbg" "warty"))))
    ("ygbby" "gater" ("bgyyy" "earth") ("bgbyy" "early")
     ("ggbgg" "gamer" ("ggbgg" "gayer" ("ggbgg" "gazer")))
     ("bgygg" "taker" ("ggbgg" "tamer" ("ggbgg" "taper"))) ("bgbgy" "harem")
     ("bgggg" "cater"
      ("bgggg" "eater" ("bgggg" "hater" ("bgggg" "later" ("bgggg" "water")))))
     ("ygbgg" "eager" ("bgggg" "lager" ("bgggg" "wager")))
     ("bgbgg" "paler" ("bgygg" "layer")
      ("ggbgg" "paper" ("ggbgg" "parer" ("ggbgg" "payer"))) ("ygbgg" "caper")
      ("bgggg" "baler")
      ("bgbgg" "baker" ("bgggg" "maker") ("bgbgg" "wafer" ("ggbgg" "waver")))))
    ("bgbyb" "salon" ("ygbgg" "mason") ("ygyby" "nasal")
     ("gggbb" "sally" ("gggbg" "salty") ("gggbb" "salad")) ("gggyb" "salvo")
     ("ggybb" "sadly") ("ggbby" "sandy" ("ggybb" "sauna")) ("ggbgb" "savoy")
     ("ggbbb" "sappy" ("ggbbg" "saucy" ("ggbbg" "savvy"))) ("ygybb" "basal")
     ("ygbby" "nasty")
     ("ygbbb" "pasha" ("bggyb" "hasty") ("gggbg" "pasta") ("gggbb" "pasty")
      ("bggbb" "tasty")))
    ("yybyy" "shear" ("gbggg" "smear" ("gbggg" "spear" ("gbggg" "swear"))))
    ("bybgy" "beast" ("bgggb" "leash")
     ("bgggg" "feast" ("bgggg" "least" ("bgggg" "yeast"))))
    ("bbbgy" "thesp" ("bgggb" "chess") ("ygggb" "chest")
     ("bbggb" "bless" ("bbggg" "guess")) ("bbggy" "poesy")
     ("ybggb" "guest" ("bgggg" "quest")) ("byygb" "welsh") ("byggb" "flesh"))
    ("ybbbb" "duroc" ("ybygb" "brood") ("bbygy" "color" ("gybgy" "crook"))
     ("ybyyy" "chord" ("gbgyg" "crowd")) ("bbyby" "crypt")
     ("gbygb" "drool" ("gyygb" "donor") ("ggggb" "droop"))
     ("gbyyb" "dowry" ("gybyb" "droll") ("gyyyb" "drown")) ("gyybb" "drunk")
     ("gbybb" "dryly") ("ybyyb" "fjord" ("gbgyg" "frond") ("bbygy" "hydro"))
     ("bgggb" "furor" ("bgggg" "juror")) ("bygyb" "forum")
     ("bggby" "curly" ("gggbg" "curry" ("gggbg" "curvy")) ("yggyb" "lurch"))
     ("bbgbb" "myrrh") ("byyyy" "court" ("gyyyb" "croup") ("yyyyb" "occur"))
     ("yyyyb" "gourd" ("byyyg" "proud")) ("bygbb" "thrum")
     ("bbgyy" "porch" ("bggyb" "corny") ("bgggg" "torch"))
     ("bbggb" "throb" ("bbggb" "moron") ("ggggb" "throw"))
     ("bbyyy" "crony" ("gggbb" "crock") ("gggyb" "crown") ("yggbb" "frock"))
     ("byyby" "crumb" ("gygbb" "churn") ("ggggb" "crump") ("yggbb" "truck"))
     ("bggyb" "turbo")
     ("bggbb" "furry" ("bggbb" "burnt") ("bgggg" "hurry")
      ("bggbg" "burly" ("bggbg" "murky")))
     ("bgygb" "humor" ("bgggg" "tumor") ("bgbgg" "tutor"))
     ("bbygb" "broom" ("ggggb" "brook") ("byggb" "floor") ("byygb" "honor")
      ("byygy" "motor") ("bgggb" "proof" ("ygggb" "troop")) ("bgggg" "groom"))
     ("ybgyb" "wordy" ("gggyb" "world"))
     ("bbgyb" "forth" ("gggbb" "forgo") ("ggggb" "forty") ("bggby" "horny")
      ("bggbg" "morph") ("bggbb" "lorry" ("bgggg" "worry"))
      ("bgggg" "north" ("bgggg" "worth")))
     ("bbyyb" "frown" ("gggby" "front") ("gggbb" "froth")
      ("bgggg" "brown" ("bgggg" "grown")) ("bggby" "prong")
      ("bgggb" "growl" ("bgggg" "prowl")) ("bygbg" "thorn") ("bygbb" "glory")
      ("bggbb" "broth" ("bggbb" "proxy") ("bggyb" "troll")) ("bggyy" "wrong"))
     ("byybb" "brunt" ("gygbb" "blurb") ("gygbg" "blurt") ("bggbb" "gruff")
      ("bgggg" "grunt") ("bgggy" "trunk")
      ("bggby" "truly" ("gggbb" "trump" ("gggbb" "truth"))) ("bgggb" "wrung"))
     ("bbybb" "wryly")
     ("byyyb" "group" ("byggb" "flour") ("ggggb" "grout") ("bgggb" "trout")
      ("byyyb" "mourn")))
    ("bbbgg" "loose" ("ybggg" "close") ("ggbgg" "louse")
     ("bgggg" "goose" ("bgggg" "moose" ("bgggg" "noose"))) ("bybgg" "obese")
     ("ybbgg" "pulse")
     ("bbbgg" "dense" ("bgbgg" "geese") ("bgggg" "sense" ("bgggg" "tense"))
      ("bybgg" "these"))
     ("bbggg" "chose" ("bgggg" "those" ("bgggg" "whose")))
     ("bgbgg" "copse" ("bgygg" "posse") ("bgbgg" "house" ("bgggg" "mouse"))))
    ("bybyb" "stalk" ("ybggb" "psalm") ("gbgyg" "slack") ("gygyb" "slant")
     ("gbgyb" "shawl" ("gbgby" "slang")) ("gyggb" "shalt")
     ("gbgby" "shaky" ("gbggg" "snaky"))
     ("gbggb" "scald" ("ggggb" "scalp" ("ggggb" "scaly"))
      ("gbggb" "shall" ("gbggg" "small")))
     ("gyyyb" "splat") ("ggggb" "stall") ("gggbg" "stack" ("gggbg" "stank"))
     ("gggbb" "staff" ("gggbb" "stamp" ("gggbb" "stand")))
     ("gbybb" "scuba" ("gbgby" "squad") ("gyyby" "sumac")) ("gyybb" "squat")
     ("gbgbg" "shank" ("gggbg" "shack") ("gbgbg" "smack") ("gbgyg" "snack")
      ("gbggg" "spank"))
     ("gygbb" "scant" ("gbgbg" "shaft") ("gbgby" "swath"))
     ("gbgbb" "swamp" ("gbggg" "scamp") ("gbgbb" "shady") ("gygby" "spawn")
      ("gbgby" "soapy"))
     ("gbyyb" "shoal") ("yyybb" "ascot") ("ybyyb" "usual") ("ybgbb" "chaos")
     ("ybybb" "assay"))
    ("yybbb" "acorn" ("ggyyb" "actor") ("gbggg" "adorn") ("gbbgy" "angry")
     ("gbggb" "abort" ("gbggb" "agora")) ("gbyyg" "apron") ("gbgyb" "aroma")
     ("gbyyb" "abhor" ("gbbyy" "aorta") ("gybgg" "arbor")
      ("gbbgg" "ardor" ("ggbgg" "armor")) ("gbbgy" "arrow"))
     ("gbbyb" "altar" ("gbbgy" "array") ("gbbbg" "augur"))
     ("gbbgb" "alarm" ("gbggb" "apart" ("gbggb" "award"))) ("yyygb" "cobra")
     ("yygyb" "croak") ("yybgb" "chard" ("ggggb" "charm" ("ggggb" "chart")))
     ("ybggb" "flora") ("yybyy" "crank") ("ybgyg" "groan") ("yyyyb" "coral")
     ("ybyyg" "organ") ("ybygb" "board" ("bgggg" "hoard") ("byggb" "ovary"))
     ("ybgyb" "broad")
     ("ybbyg" "brawn" ("bgggg" "drawn" ("bgggg" "prawn")) ("ygybg" "urban"))
     ("ybyyb" "foram" ("byyyb" "bravo") ("ggggb" "foray") ("bgygy" "molar")
      ("bgggy" "moral") ("bgggb" "borax") ("bgygb" "polar"))
     ("ybbgb" "quart" ("bgggb" "guard") ("ggggb" "quark") ("byygy" "ultra")
      ("byygb" "umbra") ("bbggb" "dwarf" ("byggg" "wharf")))
     ("yybyb" "track" ("yggyb" "craft")
      ("bggyb" "cramp" ("gggbb" "crawl" ("gggbb" "crazy"))) ("ggggb" "tract")
      ("bgggg" "crack" ("bgggg" "wrack")))
     ("ybbyy" "grand" ("bgggg" "brand") ("bgggy" "drank") ("ggggb" "grant")
      ("bgggb" "frank" ("bgggg" "prank")) ("byyyb" "lunar"))
     ("ybbyb" "thraw" ("bbyyy" "brawl" ("bgggg" "drawl"))
      ("bbyyb" "drama" ("yggbb" "fraud") ("bggbb" "gravy")) ("bbggb" "mural")
      ("byyyb" "graph") ("ybyyb" "draft" ("bgggg" "graft")) ("gbyyy" "trawl")
      ("gbyyb" "tramp") ("yyyyy" "wrath")))
    ("ybbyb" "short" ("ggggb" "shorn") ("ggbyb" "shrub" ("ggggb" "shrug"))
     ("gbygb" "sorry") ("gbgyb" "scour") ("gbggg" "snort" ("gbggg" "sport"))
     ("gbbgb" "slurp" ("gbggy" "spurn"))
     ("gbggy" "stork" ("ggggb" "storm" ("ggggb" "story"))) ("gbbyg" "strut")
     ("gbbgg" "spurt") ("gbggb" "scorn" ("gbggb" "sword") ("gbggg" "sworn"))
     ("gbbyb" "scrub" ("ggggb" "scrum") ("gbgyb" "surly") ("gbggb" "syrup"))
     ("ybbgb" "usurp") ("ybyyy" "torus"))
    ("bggbb" "faint" ("gggby" "faith") ("bgggg" "paint" ("bgggg" "taint"))
     ("bggbb" "daily" ("bgggg" "gaily")))
    ("bgbbb" "canty" ("ggbbg" "cabby" ("ggbbg" "caddy"))
     ("gggbg" "candy" ("gggbg" "canny")) ("gggbb" "canal" ("gggbb" "canon"))
     ("ggbyb" "caput" ("ggbby" "catch")) ("ggbgg" "catty")
     ("ggbbb" "cabal" ("ggbgb" "cacao") ("ggbby" "caulk")) ("yggbg" "fancy")
     ("ygybb" "bacon") ("ygbyg" "tacky")
     ("bgbyg" "fatly" ("ygybg" "taffy") ("bgygg" "tally") ("bgybg" "tabby"))
     ("bggyg" "tangy") ("bggyb" "tango")
     ("bgbgg" "batty" ("bgggg" "fatty" ("bgggg" "patty" ("bgggg" "tatty"))))
     ("bgyyg" "tawny")
     ("bgyyb" "talon" ("ygbgg" "baton") ("ygyby" "natal") ("ggbby" "taunt")
      ("ygbby" "daunt"
               ("bgggg" "gaunt" ("bgggg" "haunt" ("bgggg" "jaunt" ("bgggg" "vaunt"))))))
     ("ygbbb" "havoc" ("bgbby" "macaw") ("ygbyy" "macho")) ("ygbbg" "wacky")
     ("bgybb" "naval" ("ygbyb" "fauna") ("ygbgb" "pagan") ("ygbbb" "wagon"))
     ("bgbgb" "waltz")
     ("bggbg" "manly" ("bggyg" "lanky") ("gggbg" "mangy")
      ("bggbg" "dandy" ("bggbg" "fanny" ("bgggg" "nanny")) ("bgggg" "handy")))
     ("ygbyb" "batch"
      ("bgggg" "hatch"
               ("bgggg" "latch" ("bgggg" "match" ("bgggg" "patch" ("bgggg" "watch"))))))
     ("bgbbb" "gamma" ("bgyby" "madam") ("bgyyy" "madam") ("ygygg" "magma")
      ("bggyb" "mambo") ("bgggg" "mamma") ("bgbby" "papal") ("bgbbg" "kappa")
      ("ygbbb" "laugh"))
     ("ygbyy" "yacht") ("bgbby" "bayou" ("bggbb" "kayak"))
     ("bgbyb" "fault" ("bgyby" "datum") ("ggbyy" "fatal") ("bgybg" "gamut")
      ("bgggg" "vault") ("bgbby" "taboo"))
     ("bggbb" "banal" ("gggbb" "banjo") ("bggbb" "mango") ("bggyb" "manga"))
     ("bgbbg" "badly" ("ggbbg" "baggy") ("ggbyg" "balmy") ("ggybg" "bawdy")
      ("bgygg" "dally") ("bgybg" "gaudy") ("bgggg" "madly")
      ("bggbg" "daddy" ("bgggg" "paddy")) ("bgbgg" "gayly")
      ("bgbbg" "gamay" ("ggbbg" "gawky") ("bggbg" "mammy")
               ("bgbbg" "happy" ("bgbbg" "jazzy")))))
    ("ygbyb" "satyr" ("ggbbg" "savor")) ("bgbyy" "easel")
    ("bgybb" "panic" ("bgygy" "cabin") ("bgbyy" "cacti") ("bgggb" "mania")
     ("bgggg" "manic") ("ggbgb" "patio") ("bgbgy" "cavil" ("ygbgb" "tacit"))
     ("ygbgb" "vapid") ("bgbgg" "magic")
     ("bgbgb" "hakim" ("ggbgb" "habit") ("bgbgg" "maxim") ("bgbgb" "valid")
      ("bgbgy" "mafia")))
    ("bgbby" "laten" ("ggbgg" "laden") ("ggbgb" "label" ("ggbgg" "lapel"))
     ("ygbgy" "navel" ("ygbgg" "panel")) ("bgggb" "matey") ("bgggg" "eaten")
     ("bgygg" "taken") ("bgygb" "cadet" ("ygbgg" "facet")) ("ygygb" "valet")
     ("ygbgb" "bagel" ("bgygg" "gavel") ("bgbgg" "camel" ("bgbgg" "hazel")))
     ("bgbgb" "cagey" ("ggbgb" "cameo"))
     ("bgbgg" "waken" ("bgggg" "oaken") ("ggbgg" "waxen") ("bgbgg" "haven")))
    ("yybby" "derat" ("byyyg" "alert" ("gbggg" "avert")) ("ygygb" "cedar")
     ("ggygb" "debar") ("gyygb" "dread" ("ggggb" "dream")) ("bgggb" "feral")
     ("ygyyb" "beard" ("bgggg" "heard"))
     ("byyyb" "amber" ("gbbyy" "arena") ("gbbgg" "anger") ("ybbyy" "opera"))
     ("yyygb" "bread") ("bgyyg" "heart") ("bggyy" "terra") ("bgyyy" "teary")
     ("yyygy" "tread") ("byygg" "great" ("bgggg" "treat"))
     ("byyyy" "after" ("gbggg" "alter") ("ybgyy" "extra"))
     ("byygb" "break" ("byggb" "clear") ("bgggb" "cream")
      ("bgggg" "creak" ("bgggg" "freak" ("bgggg" "wreak"))))
     ("bgyyb" "learn" ("ygggb" "pearl") ("bgggb" "weary") ("bgggg" "yearn")
      ("bgygb" "zebra")))
    ("bbgyy" "shied" ("gbggg" "spied") ("gbggb" "spiel"))
    ("ybbyy" "speer" ("ybygg" "ester") ("yybgg" "poser") ("gbyby" "serum")
     ("gbygg" "sever" ("ggbgg" "sewer")) ("gggby" "sperm") ("gbgby" "stern")
     ("gybgg" "super") ("gbbgg" "sober" ("ggbgg" "sower") ("gbbgg" "surer"))
     ("gbggg" "sheer" ("gbggg" "sneer" ("gbggg" "steer")))
     ("gbbgy" "screw" ("gbggg" "shrew")) ("ybbgg" "loser" ("bbygg" "usher")))
    ("bbyby" "lined" ("bygyy" "denim") ("yybyy" "devil") ("bgyyg" "fiend")
     ("yybgb" "impel") ("byygy" "index") ("yyygb" "inlet") ("ggbgb" "libel")
     ("ggggb" "linen") ("ggygb" "liken") ("bybyy" "debit" ("ygbgb" "medic"))
     ("yyyyb" "elfin") ("ygbgb" "filet" ("bgygb" "pixel"))
     ("bybyb" "befit" ("bybgb" "equip") ("bybgy" "ethic"))
     ("bybyg" "fetid" ("bgygg" "tepid")) ("byyyb" "begin" ("bybyy" "inept"))
     ("yybyb" "helix") ("bgbgy" "dicey" ("ygbgb" "video"))
     ("bgbyb" "eight" ("ygbby" "piety")) ("bgygy" "widen")
     ("bgygb" "given" ("bgygg" "vixen")) ("bygyb" "ennui")
     ("ygbyg" "field" ("bgggg" "wield" ("bgggg" "yield"))) ("bgbgb" "bicep")
     ("bgggb" "piney"))
    ("bbyyy" "islet" ("yybyb" "sheik") ("yybyy" "stein") ("yybgb" "sinew"))
    ("yyybb" "trail" ("byggb" "chair") ("byggy" "flair")
     ("bgggg" "frail" ("bgggg" "grail"))
     ("bgggb" "braid" ("ggggb" "brain") ("bgggy" "drain") ("bgggb" "grain"))
     ("bygyb" "diary") ("byygb" "acrid") ("gygyb" "tiara")
     ("ggggb" "train" ("ggggb" "trait")) ("byyyg" "viral")
     ("byyyb" "cigar" ("ggbyy" "circa") ("ygbgg" "vicar")))
    ("bbyyb" "cists" ("yygbb" "music") ("yggbb" "disco") ("bygyb" "posit")
     ("bgyyb" "sight") ("bgybb" "silky" ("gggbg" "silly"))
     ("bgygb" "sixth" ("ggggb" "sixty"))
     ("byybb" "solid" ("gyygb" "spoil") ("gbbgb" "squib")) ("yyyyb" "stoic")
     ("byyyb" "split") ("yyybb" "sonic") ("bygby" "sushi") ("bggyb" "visit")
     ("bggbb" "fishy" ("bggbb" "bison") ("bggbg" "wispy")) ("ygbbg" "ficus")
     ("bgbbg" "minus"))
    ("bybby" "tepal" ("bybyg" "angel") ("byyyb" "apnea") ("ygbgb" "begat")
     ("yybgy" "bleat" ("bgggg" "cleat") ("byygg" "eclat")) ("yyyyb" "adept")
     ("byygb" "cheap") ("yybyb" "agent" ("ybyyg" "enact") ("ybybg" "exact"))
     ("bybgy" "glean" ("bgggg" "clean") ("bgggb" "bleak") ("ggggb" "gleam"))
     ("ygbyy" "dealt" ("ggyyy" "delta") ("bggyg" "leant")) ("ygyyy" "leapt")
     ("bgbgy" "delay") ("yybyy" "exalt") ("ygbgg" "fetal" ("bgggg" "metal"))
     ("bybyb" "amend" ("gbybb" "abbey") ("gbyyb" "annex") ("yygyb" "enema")
      ("ybggb" "hyena") ("yggbb" "omega"))
     ("bgygb" "pecan") ("bgygg" "pedal" ("ggbgg" "penal")) ("bgyyb" "peach")
     ("ygygg" "petal") ("byygy" "plead") ("yyygy" "pleat")
     ("bybgb" "ahead" ("bbggg" "knead") ("bbggb" "ocean")) ("ggbyb" "teach")
     ("gybyb" "theta") ("gybgb" "tweak") ("bybyy" "abled" ("gbggb" "alley"))
     ("bgbyb" "beady" ("gggbb" "beach") ("bgggg" "heady") ("bggbg" "heavy")
      ("bgybb" "mecca"))
     ("bgbgb" "began" ("bgbgb" "decay") ("ygbgb" "kebab") ("bgggg" "vegan"))
     ("bgbgg" "decal" ("bgggg" "fecal") ("ygbgg" "medal") ("bgbgg" "legal"))
     ("bgbyy" "leafy" ("ygyyb" "fella") ("gggbb" "leach") ("gggbg" "leaky")
      ("yggbg" "mealy"))
     ("yybgb" "cheat" ("bgggg" "wheat"))
     ("ygbyb" "death" ("bggyb" "meant") ("bgggb" "meaty") ("bgggg" "heath"))
     ("bybgg" "equal"))
    ("bybyy" "steak" ("ybyyy" "askew") ("gbygb" "sedan")
     ("gbggg" "sneak" ("gbggg" "speak"))
     ("ggggb" "stead" ("ggggb" "steal" ("ggggb" "steam"))) ("gyggb" "sweat")
     ("yyyyb" "asset") ("ybyyb" "ashen") ("ybygb" "essay"))
    ("bybbg" "plate" ("yyybg" "ample" ("gbggg" "apple"))
     ("byybg" "angle" ("ggbgg" "ankle") ("gbbgg" "amble")) ("bbygg" "acute")
     ("ybgbg" "agape") ("bgggg" "elate")
     ("bggbg" "blade" ("gggbg" "blame" ("gggbg" "blaze")) ("bgggg" "glade")
      ("bggbg" "flake" ("gggbg" "flame") ("bggbg" "glaze")))
     ("gbgbg" "peace") ("gggbg" "place" ("gggbg" "plane"))
     ("bbggg" "abate" ("gbggg" "agate") ("bbggg" "ovate")) ("bbyyg" "atone")
     ("bgybg" "algae" ("ggbbg" "alone"))
     ("bbgbg" "awake" ("gbgbg" "adage" ("gbgbg" "amaze"))
      ("bbgbg" "chafe" ("bbgbg" "evade") ("bygbg" "heave")) ("bbgyg" "knave")
      ("bbggg" "quake") ("bygbg" "weave"))
     ("bygbg" "leave" ("ybgbg" "whale"))
     ("bbybg" "abode" ("gggbg" "above") ("gygyg" "adobe") ("gbggg" "anode")
      ("gbgbg" "awoke")))
    ("ybbby" "outer" ("bbgyy" "entry") ("ybbyg" "decor" ("bybgg" "error"))
     ("bybyg" "demur" ("bgggg" "femur" ("bgggg" "lemur"))) ("ybgyy" "metro")
     ("gbygg" "other") ("gbyyy" "overt")
     ("gbbgg" "odder" ("gbggg" "older" ("gbggg" "order"))
      ("gbbgg" "offer" ("gbbgg" "owner")))
     ("gbggg" "otter") ("bbggg" "deter" ("byggg" "enter") ("bgggg" "meter"))
     ("bbbgy" "creed" ("ggggb" "creek" ("ggggb" "creep"))
      ("bgggg" "breed" ("bgggg" "freed" ("bgggg" "greed")))
      ("bgggb" "green" ("bgggg" "preen")))
     ("bgbgg" "buyer" ("bgbgg" "purer" ("bgbgg" "queer"))) ("bgbyy" "query")
     ("ybyyg" "tenor") ("ybygg" "tower") ("byygg" "truer") ("bgygg" "tuber")
     ("bbyyy" "crept" ("yggbg" "erect") ("bygbg" "exert") ("byyby" "berth")
      ("bggby" "trend"))
     ("bbygg" "ether")
     ("bbygy" "beret" ("byggg" "egret") ("byygg" "greet") ("bbggy" "threw"))
     ("bybgg" "udder" ("ybbgg" "bluer") ("gbggg" "under")
      ("gbbgg" "ulcer" ("gbbgg" "upper")))
     ("bybgy" "cruel" ("bgggg" "gruel")) ("byggg" "utter") ("byyyy" "erupt")
     ("ybggg" "voter")
     ("bbbyy" "clerk" ("ybygb" "decry") ("byggb" "leery")
      ("ybyyb" "mercy" ("bgggb" "perch")) ("bbyyy" "jerky" ("bgggg" "perky"))
      ("bbygb" "berry" ("bgggg" "ferry" ("bgggg" "merry")))
      ("bbyyb" "derby" ("yggbg" "nerdy")) ("bbggb" "every") ("ybgyg" "wreck"))
     ("bbbgg" "fever" ("ygbgg" "defer")
      ("bybgg" "elder" ("ybbgg" "cheer") ("gbbgg" "ember")) ("ggbgg" "fewer")
      ("gybgg" "freer") ("gbbgg" "flyer") ("bgggg" "lever" ("bgggg" "never"))
      ("bgbgg" "leper" ("bgbgg" "newer"))
      ("bbbgg" "cyber" ("bgbgg" "hyper") ("bybgg" "dryer")))
     ("ybbyy" "credo" ("byyby" "heron"))
     ("ybbgg" "vower"
      ("ygbgg" "cover" ("bgggg" "hover" ("bgggg" "lover" ("bgggg" "mover"))))
      ("bgggg" "cower" ("bgggg" "lower" ("bgggg" "mower" ("bgggg" "power"))))
      ("bgygg" "wooer")
      ("bgbgg" "joker" ("bgggg" "poker")
               ("bgbgg" "boner" ("ggbgg" "boxer")
                        ("bgbgg" "comer" ("ggbgg" "corer") ("bgggg" "homer") ("bgbgg" "foyer"))
                        ("bgggg" "goner")))))
    ("bbbby" "lento" ("ygbby" "below")
     ("yybyb" "cleft" ("bygbg" "dwelt") ("yggbg" "elect") ("byybg" "exult")
      ("bggyg" "fleet"))
     ("ygbbg" "cello" ("bgggg" "hello")) ("bgbby" "decoy") ("bybgb" "empty")
     ("ggbgb" "lefty") ("ggyby" "lemon")
     ("ggbbb" "leech" ("ggbbb" "leggy") ("ggybb" "level")) ("gyybb" "lumen")
     ("bgbbg" "gecko") ("ygybb" "newly") ("ygyby" "felon" ("bgggg" "melon"))
     ("bgyby" "demon") ("yyyby" "novel" ("yybgy" "olden"))
     ("bgbgb" "depth" ("bgbgy" "hefty") ("bgbgb" "jetty") ("bgygb" "petty")
      ("bgbgg" "teeth"))
     ("bgbyg" "tempo") ("bggyb" "tenet") ("bgggb" "tenth")
     ("bgbyy" "depot" ("ggbgy" "detox")) ("byyyy" "often" ("ybygg" "token"))
     ("yybyy" "hotel" ("bygyg" "extol") ("bgggg" "motel") ("bgygg" "towel"))
     ("yyybb" "blend" ("bygyb" "kneel")) ("yyyyb" "knelt")
     ("byyyb" "event" ("ybbyg" "unmet"))
     ("bybyy" "comet" ("ggbgg" "covet") ("yybgg" "octet") ("bgygy" "totem"))
     ("bgbyb" "debut" ("bgybg" "beget") ("ygbby" "teddy") ("bgbby" "fetch"))
     ("bgybb" "begun" ("bgbby" "needy"))
     ("ygbbb" "belch" ("gggbb" "belly") ("ggybb" "bevel" ("ggbgg" "bezel"))
      ("bgybb" "jewel") ("bgggg" "welch") ("bggbb" "jelly"))
     ("bggbb" "bench" ("bgggg" "wench") ("bggbb" "penny")) ("ygbyb" "betel")
     ("byybb" "unfed" ("bgbyb" "enemy") ("bgbgg" "kneed") ("yybgb" "queen")
      ("ggbgg" "unwed") ("bybgb" "hymen"))
     ("byyby" "woven" ("bgggg" "coven") ("yybyy" "endow")
      ("bybyy" "ebony" ("gbyyg" "enjoy")) ("bygyy" "envoy") ("bgbgg" "dozen")
      ("ggbgg" "woken" ("ggbgg" "women")))
     ("bybyb" "eject" ("ybbbg" "duvet") ("bbgbg" "theft") ("ybgby" "tweed")
      ("ybgbg" "tweet"))
     ("bggby" "venom")
     ("yybbb" "cupel" ("bbygy" "bleep") ("gybgy" "clued") ("ybbgg" "excel")
      ("bbggg" "expel") ("ybbyy" "fleck") ("bbbyg" "dwell") ("bgbyg" "quell")
      ("bbbgg" "wheel") ("bbbyy" "elegy") ("bbyyy" "whelp") ("bbbgy" "bleed"))
     ("yybby" "dowel" ("byyyy" "elbow") ("bgbgy" "golem")
      ("bgggg" "bowel" ("bgggg" "vowel")) ("ygbgg" "model") ("bgbgg" "hovel"))
     ("bybbb" "check" ("gggbg" "cheek") ("bbybb" "embed"))
     ("bgbbb" "hedgy" ("ygbbb" "beech") ("bgyyb" "debug") ("bgbyg" "geeky")
      ("bgybg" "weedy") ("bgbbg" "beefy"))
     ("bygby" "boney" ("bgggg" "honey" ("bgggg" "money")))
     ("bybby" "epoch" ("ybyyb" "covey") ("gggbb" "epoxy") ("yyybb" "dopey")
      ("ybybb" "modem") ("ybgbb" "gooey")))
    ("bbbbb" "could" ("gbgbb" "chuck" ("gggbb" "chump") ("gggbg" "chunk"))
     ("gyyyg" "cloud") ("gyyyb" "clout")
     ("gbgyb" "clunk" ("gggbg" "cluck") ("gggbb" "clump") ("ggggb" "clung"))
     ("ggbyb" "colon") ("ggbby" "condo") ("ggbbb" "comfy" ("ggbbb" "conch"))
     ("gggbb" "couch" ("gggbb" "count") ("gggbg" "cough")) ("ggbgb" "coyly")
     ("gybyb" "clonk" ("gggbg" "clock") ("gggbb" "cloth") ("gggyb" "clown"))
     ("gybbb" "chock") ("bggby" "doubt" ("gggbb" "dough")) ("bbygy" "dully")
     ("ybyby" "duchy" ("ggyyb" "dutch"))
     ("bybyg" "blond" ("gggbg" "blood") ("bggbg" "flood"))
     ("bgbgy" "dolly" ("ygbgg" "godly")) ("yybbb" "knock") ("ybbyb" "lynch")
     ("bgbyy" "moldy") ("bbygb" "bully" ("bgggg" "fully" ("bgggg" "gully")))
     ("ybyyb" "gulch" ("bgyyb" "lucky") ("bgygg" "lunch") ("bgggg" "mulch"))
     ("yybyb" "block" ("bgggg" "flock")) ("bybgy" "oddly") ("byyby" "outdo")
     ("bybgb" "knoll") ("ybgyb" "pluck")
     ("bbgyb" "flunk" ("yggbb" "bluff") ("bgggb" "blunt") ("ggggb" "flung")
      ("gggbb" "fluff") ("bggbb" "plumb" ("ggggb" "plump")) ("bgggg" "plunk"))
     ("ygbbb" "botch" ("bgggg" "notch") ("bgbgg" "pooch")) ("bgggb" "moult")
     ("bbyyb" "bulky" ("bgybg" "lumpy") ("bggbg" "pulpy"))
     ("bbbbb" "nymph" ("bgyyb" "pygmy")) ("bgyby" "donut")
     ("yggbb" "pouch" ("bgggg" "touch" ("bgggg" "vouch")))
     ("byyyb" "flout" ("byggb" "ghoul"))
     ("bybbb" "phony" ("bbgyb" "known") ("gggbb" "photo") ("bgggb" "thong")
      ("yggbb" "whoop"))
     ("bbgbb" "thumb" ("ggggb" "thump")) ("bgyyb" "mogul")
     ("bgbby" "dowdy" ("ggbyg" "dodgy") ("gggbg" "downy") ("bgggg" "howdy")
      ("bgbgg" "goody" ("bgggg" "moody")) ("ygbgg" "toddy") ("bgygg" "woody"))
     ("bgbgb" "hollo" ("ggggb" "holly") ("ggbgb" "hotly") ("bgygb" "lowly")
      ("bgggb" "folly" ("bgggg" "golly" ("bgggg" "jolly"))) ("bgbgb" "nobly")
      ("bgbgy" "wooly"))
     ("bgggg" "would")
     ("bggbg" "bound"
      ("bgggg" "found"
               ("bgggg" "hound" ("bgggg" "mound" ("bgggg" "pound" ("bgggg" "wound"))))))
     ("bbyby" "dumpy" ("gggbg" "dummy") ("ygybg" "muddy") ("ygbyg" "pudgy")
      ("ygbbg" "buddy"))
     ("bbbyb" "glyph" ("byygg" "lymph"))
     ("bgbyb" "looby" ("ggbgg" "lobby") ("gggbg" "loopy") ("ggbbg" "lofty")
      ("ygbby" "polyp"))
     ("bggbb" "mouth" ("bggbg" "bough") ("gggyb" "mount") ("bgggb" "pouty")
      ("bggyg" "tough") ("bggbb" "young") ("bgggg" "youth"))
     ("ybybb" "bunch" ("ggbgg" "butch")
      ("bgggg" "hunch" ("bgggg" "munch" ("bgggg" "punch"))) ("byyyb" "uncut")
      ("bgbgg" "hutch") ("bgbyb" "mucky"))
     ("byybb" "gumbo" ("bgyyy" "buxom") ("bgggg" "jumbo") ("ygbby" "ought")
      ("ygbbg" "outgo") ("bgbbg" "junto") ("bgbby" "quoth"))
     ("bbybb" "bumph" ("ggbbb" "buggy" ("ggbbg" "bunny")) ("bgggg" "humph")
      ("bgbby" "hunky") ("bgggb" "jumpy") ("bgbyb" "puffy" ("ggbbg" "putty"))
      ("bgbbb" "funky" ("gggbg" "funny") ("ggbbg" "fuzzy") ("bgybg" "nutty"))
      ("bggbb" "gummy" ("bgggg" "mummy")) ("bgbgb" "guppy" ("bgggg" "puppy")))
     ("bybyb" "bloom" ("gggbb" "blown") ("bgggg" "gloom") ("bybgb" "nylon")
      ("bggbb" "flown"))
     ("bgbbb" "boozy" ("ggybb" "bongo") ("gggbb" "booth")
      ("gggbg" "booby" ("gggbg" "booty")) ("ggbbg" "bobby") ("bgbbb" "month")
      ("bgybb" "motto") ("bggbb" "tooth") ("bgbbg" "foggy" ("bgbbg" "poppy"))
      ("bggbg" "goofy") ("bgggg" "woozy") ("ygbbg" "hobby")))
    ("ybybb" "droit" ("byggb" "choir") ("gybyy" "dirty") ("ggbgb" "druid")
     ("bgbgg" "fruit") ("bgggb" "broil" ("bgggb" "groin")) ("bggyb" "irony")
     ("bybyb" "birch" ("byyyb" "incur") ("bggbb" "girly")) ("byyyy" "intro")
     ("bgygg" "orbit") ("bygyb" "ivory") ("yybgb" "lurid") ("bybgb" "lyric")
     ("byyyb" "micro" ("ggbyy" "minor") ("bgbyy" "vigor"))
     ("bybyy" "birth" ("bgggg" "girth" ("bgggg" "mirth"))) ("byygb" "curio"))
    ("ybyyb" "sprig" ("gyggb" "strip") ("ybyyb" "visor") ("ybgyb" "virus"))
    ("bbbyb" "stonk" ("gybgb" "shunt") ("gbbbg" "shuck" ("gbgbg" "skulk"))
     ("gygyb" "snout") ("gbbyg" "snuck") ("gbgby" "smoky") ("gbygb" "sound")
     ("gyybb" "south")
     ("gbgbg" "shock" ("gggbg" "shook") ("gbggg" "smock") ("gbgbg" "spook"))
     ("gbbgg" "skunk" ("gbggg" "slunk" ("gbggg" "spunk"))) ("ggggb" "stony")
     ("gggbg" "stock")
     ("gggbb" "stoop" ("ggggb" "stood" ("ggggb" "stool")) ("gggbg" "stomp")
      ("gggbb" "stout"))
     ("ggbbg" "stuck") ("ggbgg" "stunk") ("ggbgb" "stung" ("ggggb" "stunt"))
     ("ggbbb" "stymy" ("ggbbg" "study") ("ggbbb" "stuff") ("ggbgb" "stump"))
     ("gbbby" "skull" ("gyyyb" "sulky"))
     ("gbgbb" "scowl" ("gggby" "scold") ("gggbb" "scoff" ("gggbb" "scoop"))
      ("gbggb" "showy") ("gbgby" "sloop") ("gbgbb" "spoof") ("gbgbg" "spool")
      ("gbgyb" "swoop"))
     ("gygbb" "shoot" ("gggbg" "shout") ("gygby" "sloth") ("gygyy" "sooth")
      ("gbgyy" "sooty") ("gbgbg" "scout" ("gbggg" "spout")))
     ("gbgyb" "shown" ("gbgby" "snoop") ("gbggy" "snowy") ("gbgbg" "spoon")
      ("gbgyg" "swoon"))
     ("gbbgb" "slung" ("gbygb" "sunny") ("gbggg" "swung")) ("gbbyb" "snuff")
     ("gbyyb" "synod")
     ("gbbbb" "shyly" ("gbggg" "slyly") ("gbbgg" "sully") ("gbbyb" "slump"))
     ("gbybb" "soggy") ("ybyyb" "bonus") ("yyybb" "gusto")
     ("yybbb" "gluts" ("gbygy" "gusty") ("byygy" "lusty")
      ("bbygy" "dusty" ("bgggg" "musty")))
     ("ybybb" "focus" ("bgbby" "bosom") ("bgggg" "locus"))
     ("ybbby" "dusky" ("bgggg" "husky" ("bgggg" "musky")))
     ("ybbbb" "bumfs" ("ggbby" "bushy") ("bgybg" "mucus") ("bgyby" "mushy")
      ("bggbg" "humus") ("bgbby" "pushy") ("bgbbg" "lupus")))
    ("bbbbg" "lunge" ("ygbgg" "bulge") ("ygbyg" "bugle") ("bgbyg" "fugue")
     ("ybbyg" "globe" ("gggbg" "glove")) ("bybgg" "gouge")
     ("gbbgg" "ledge" ("gbggg" "lodge")) ("bbyyg" "gnome")
     ("ybybg" "clone" ("byyyg" "noble")) ("bgygg" "nudge")
     ("bggbg" "dunce" ("bgggg" "ounce")) ("bbybg" "ozone" ("bbggg" "phone"))
     ("yybbg" "flume" ("bggbg" "elude") ("gggbg" "fluke" ("gggbg" "flute"))
      ("bygbg" "boule") ("bgggg" "plume"))
     ("bgbgg" "budge" ("bgggg" "fudge" ("bgggg" "judge"))) ("ygbbg" "tulle")
     ("bgbbg" "butte" ("bgbbg" "queue") ("bgbgg" "quote")) ("yyybg" "uncle")
     ("byybg" "undue")
     ("bybbg" "chute" ("gbgbg" "coupe") ("ybgbg" "deuce") ("bbgyg" "etude"))
     ("bygbg" "venue") ("bybyg" "vogue")
     ("bbbgg" "hedge" ("bgggg" "wedge") ("bbggg" "dodge"))
     ("bbgbg" "fence" ("bgggg" "hence" ("bgggg" "pence")) ("bggbg" "penne"))
     ("ybbbg" "coble" ("bbygg" "belle") ("byyyg" "bloke") ("gybyg" "clove")
      ("gbbgg" "cycle") ("bbbyg" "delve" ("bggbg" "melee")) ("bybgg" "whole")
      ("bybyg" "elope"))
     ("bbbbg" "theme" ("bgbbg" "choke") ("bbyyg" "emcee") ("bbygg" "femme")
      ("bbbbg" "booze") ("ggbgg" "thyme") ("gbybg" "tepee") ("bbybg" "evoke")))
    ("bbybg" "tinge" ("bygyg" "genie") ("bgggg" "binge" ("bgggg" "hinge"))
     ("yybbg" "cutie") ("bgbgg" "bilge" ("bgygg" "liege") ("bgbgg" "midge"))
     ("bgybg" "niche" ("ggybg" "niece"))
     ("bgbbg" "biome" ("ggbbg" "bible") ("bggbg" "diode")
      ("bgbbg" "civie" ("ygbbg" "piece") ("bgbbg" "pique") ("bgbgg" "pixie")))
     ("ggbbg" "tilde" ("ggbbg" "tithe") ("ggybg" "title")) ("yyybg" "untie")
     ("ygbbg" "lithe") ("bggbg" "mince" ("bgggg" "wince"))
     ("bybbg" "belie" ("ybbyg" "imbue") ("bbbgg" "movie")))
    ("bybbb" "alant" ("gbgbg" "adapt") ("gybbg" "adult")
     ("ggbbg" "allot" ("ggbyg" "aloft")) ("ggbgb" "along")
     ("ggbbb" "allow" ("ggggb" "alloy") ("ggbbb" "album") ("ggbgb" "aloof")
      ("ggbyb" "aloud"))
     ("ggybb" "allay" ("ggbyb" "alpha")) ("gbbgb" "agony" ("gyggb" "among"))
     ("gbbyb" "annoy") ("gybby" "aptly" ("gbygb" "atoll"))
     ("gbbbg" "abbot" ("ggbyg" "about") ("gbbyg" "adopt") ("gbbgg" "afoot"))
     ("gbbyy" "aunty")
     ("gybbb" "afoul" ("gbyby" "aglow") ("gbbby" "amply" ("gbggg" "apply"))
      ("gybgg" "awful"))
     ("gbgbb" "aback") ("gybyb" "annul") ("ygbbb" "cloak")
     ("ygbbg" "bloat" ("bgggg" "float" ("bgggg" "gloat"))) ("ybgbb" "guava")
     ("bbgyb" "knack") ("yygbb" "koala") ("bygby" "loath")
     ("bggbb" "black" ("bggyb" "clamp") ("bggby" "flaky")
      ("bgggg" "clack" ("bgggg" "flack")))
     ("bgggb" "blank" ("ggggb" "bland") ("bgggb" "clang" ("bgggy" "gland"))
      ("bgggg" "clank" ("bgggg" "flank" ("bgggg" "plank"))))
     ("bgggg" "plant") ("bbggg" "chant") ("yybyy" "tonal")
     ("ybbyy" "junta" ("bbgyg" "tonga"))
     ("ybbby" "today" ("yybyb" "quota") ("ggbgb" "topaz"))
     ("bbggy" "thank" ("gbggb" "twang")) ("yggbb" "llama" ("bggbg" "plaza"))
     ("yybby" "octal" ("ybggg" "total") ("bbygg" "tubal"))
     ("bbgbb" "chaff" ("gggbb" "champ") ("gygbb" "coach") ("bbgyb" "foamy")
      ("ybgbb" "quack") ("yggbb" "whack"))
     ("bygbb" "chalk" ("bbgyb" "loamy") ("bbggb" "qualm"))
     ("ybbyb" "gonad" ("bgygg" "nomad") ("bbygb" "human") ("bgygb" "woman"))
     ("yybbb" "local" ("ybbgb" "bylaw") ("ggbgg" "loyal") ("bgbgg" "modal")
      ("bybgg" "offal") ("bbbgg" "pupal") ("bgggg" "focal" ("bgggg" "vocal"))
      ("ygbyb" "polka"))
     ("yybyb" "zonal")
     ("ybbbb" "comma" ("ggbbg" "cocoa") ("bgbgg" "dogma") ("ygybg" "mocha")
      ("bgbbg" "vodka")))
    ("bbybb" "linty" ("yybbg" "imply") ("bybyg" "itchy") ("yybby" "idyll")
     ("gggbb" "lingo") ("ggbyb" "light" ("ggbbg" "limit"))
     ("ggbbb" "lipid" ("ggbbb" "limbo") ("ggbgg" "livid"))
     ("gybbb" "logic" ("gbbgy" "lucid")) ("gyybb" "login") ("bgggg" "minty")
     ("ygbyb" "pilot") ("bgggb" "ninth" ("bgggb" "pinto"))
     ("bygbb" "conic" ("bgggg" "ionic") ("bbgyb" "fungi"))
     ("yybbb" "fluid" ("gybgb" "folio") ("bybyb" "igloo") ("byygb" "pupil"))
     ("bgyyb" "night") ("ygbgb" "filth") ("bygyb" "tonic" ("gbggg" "tunic"))
     ("yyyyb" "unlit" ("ggygy" "until"))
     ("byyyb" "ingot" ("ggbbg" "input") ("yybyy" "toxin") ("ygbbg" "unfit"))
     ("byybb" "undid" ("bgbyb" "inbox") ("yybgb" "cumin") ("ggbgb" "unzip"))
     ("yybyb" "tulip") ("yggby" "vinyl")
     ("bybyb" "optic" ("ybggb" "motif") ("yyygg" "topic") ("ybygg" "toxic")
      ("ybygb" "vomit"))
     ("bgbgb" "ditto" ("bgbgb" "fifth") ("ygbgb" "width"))
     ("ygbbg" "filly" ("gggbg" "filmy") ("bgbgg" "dimly") ("bggbg" "milky")
      ("bgggg" "billy" ("bgggg" "dilly" ("bgggg" "hilly" ("bgggg" "willy")))))
     ("bgbyg" "pithy")
     ("bgbgg" "bitty" ("bgbgg" "fifty")
      ("bgggg" "ditty" ("bgggg" "kitty" ("bgggg" "witty"))))
     ("bygby" "cynic") ("ygbbb" "civil" ("bgygg" "vigil"))
     ("bggbb" "cinch" ("bggbb" "bingo" ("bgggg" "dingo") ("bggbb" "minim"))
      ("bgggg" "finch" ("bgggg" "pinch" ("bgggg" "winch"))))
     ("bggbg" "dinky" ("gggbg" "dingy") ("yggbg" "windy") ("bggbg" "ninny")
      ("bgggg" "kinky" ("bgggg" "pinky")))
     ("bgbbb" "vivid" ("bgggb" "civic") ("bgbgb" "mimic") ("bgbby" "widow")
      ("bgbbb" "hippo"))
     ("bgbbg" "dippy" ("ggbbg" "dizzy") ("bgybg" "picky" ("ggbbg" "piggy"))
      ("ygbbg" "biddy" ("bgggg" "giddy")) ("bgbbg" "fizzy" ("ygbbg" "jiffy"))
      ("bgbgg" "wimpy") ("bgggg" "hippy"))
     ("bgbyb" "wight" ("bggbg" "bigot" ("bggbg" "digit"))
      ("bgggg" "fight" ("bgggg" "might" ("bgggg" "tight"))) ("bgbby" "timid")
      ("bgbyy" "ditch" ("bgggg" "hitch" ("bgggg" "pitch"))) ("ggbyy" "witch")
      ("bgbbg" "pivot"))
     ("bybbb" "comic" ("gbbgg" "cubic") ("bbggb" "humid") ("bybgb" "ovoid")
      ("bbbgg" "pubic")))
    ("bbbyy" "spelt" ("yyybb" "pesky") ("gyyby" "setup") ("gygyb" "sleep")
     ("gbgyg" "sleet") ("gygyg" "slept") ("gbgyb" "sleek") ("gbggg" "smelt")
     ("gbgbb" "seedy" ("gygbb" "sheen")) ("ggggb" "spell") ("gggbg" "spent")
     ("gggbb" "speed" ("gggbg" "spend") ("gggbb" "speck")) ("gbgyy" "steel")
     ("gygby" "steep") ("gbgby" "steed") ("gygbb" "sheep" ("gbggg" "sweep"))
     ("gbgbg" "sheet" ("gbgbg" "scent") ("gbggg" "sweet"))
     ("gbggb" "shelf" ("ggggb" "shell") ("gbggb" "smell" ("gbggg" "swell")))
     ("gygbg" "swept") ("gbybb" "semen" ("ggbgg" "seven")) ("yyyby" "pesto")
     ("ybybg" "onset" ("bbggg" "beset") ("bgggg" "unset")) ("ygybg" "upset")
     ("ybyby" "testy" ("ygybb" "fetus") ("yyybb" "ethos") ("bgggg" "zesty"))
     ("ybybb" "bused" ("bbggb" "nosey")))))
#+not-compiled-in-just-here-for-reference
(let* ((answers (read-words "answers.txt"))
       (words (remove-duplicates (append answers
                                         (read-words "other-guesses.txt"))
                                 :test #'string=))
       (tree (time (precompute-guesser-tree words #'greedy-guess :answers answers))))
  (with-open-file (*standard-output* "tree.lisp"
                                     :if-does-not-exist :create
                                     :if-exists :supersede
                                     :element-type 'character)
    (write tree)))

(defun precompute-guesser-tree (words guesser &key answers)
  (let* ((answers (or answers
                      words))
         (guess (funcall guesser words :answers answers))
         (eql-words-answers (eql words answers))
         (words (remove guess words :test #'string=))
         (answers (if eql-words-answers
                      words
                      (remove guess answers :test #'string=))))
    (list* guess
           (loop :for score :in (remove-duplicates (loop :for w :in words
                                                      :collect (score-guess guess w))
                                                   :test #'string=)
              :for filter-info := (list guess score)
              :for remaining-words := (filter words filter-info)
              :for remaining-answers := (if eql-words-answers
                                            remaining-words
                                            (filter answers filter-info))
              :when remaining-answers
              :collect (list* score (precompute-guesser-tree remaining-words guesser :answers remaining-answers))))))

(defun prune-guess-tree (tree score)
  (rest (assoc score (rest tree) :test #'string=)))

(defun make-guess-tree-iterator (&optional (tree *precomputed-tree*))
  (let ((cur tree))
    (lambda (&optional (result "ggggg"))
      (cond
        ((string= result "ggggg")
         (setq cur tree))
        (t
         (setq cur (prune-guess-tree cur result))))
      (first cur))))
